/**
 * ============================================================================
 * CATHEDRAL LITURGICAL CALENDAR ENGINE (大教堂礼历引擎)
 * ============================================================================
 *
 * Functions for generating and navigating the ceremonial calendar.
 * The rhythmic spine that ties together timing, story, and ritual across time.
 *
 * The calendar is:
 * - Generated by the Timing Engine
 * - Interpreted by the Story Engine
 * - Embodied by the Ritual Layer
 * - Spoken by the Persona
 * - Remembered by the Memory Engine
 *
 * Created: January 2026
 * ============================================================================
 */

import {
  LiturgicalSeason,
  LiturgicalCalendar,
  LiturgicalPosition,
  LiturgicalCalendarOptions,
  GreatSeason,
  RitualMonth,
  RitualMonthNumber,
  StoryWeek,
  WeeklyStoryBeat,
  DailyQuadrant,
  DayQuadrant,
  RitualDay,
  TimingWindow,
  DailyTimingWindows,
  CeremonialFestival,
  FestivalType,
  SEASON_CHINESE,
  SEASON_SUBTITLES,
  SEASON_ELEMENTS,
  SEASON_STORY_ARCS,
  SEASON_RITUAL_ARCHETYPES,
  SEASON_WHISPERS,
  RITUAL_MONTH_NAMES,
  RITUAL_MONTH_CHINESE,
  RITUAL_MONTH_THEMES,
  RITUAL_MONTH_STORY_BEATS,
  RITUAL_MONTH_RITUALS,
  QUADRANT_CHINESE,
  QUADRANT_ACTIONS,
  QUADRANT_HOURS,
  WEEKLY_BEAT_CYCLE,
  WEEKLY_BEAT_DESCRIPTIONS,
  FESTIVAL_NAMES,
  FESTIVAL_CHINESE
} from './liturgyTypes';

// ============================================================================
// SEASON GENERATION
// ============================================================================

/**
 * Generate the four great seasons
 */
export function generateGreatSeasons(): GreatSeason[] {
  const seasons: LiturgicalSeason[] = ['spring', 'summer', 'autumn', 'winter'];

  return seasons.map(season => {
    const energeticTones = getSeasonalTones(season);
    const ceremonialFocus = getSeasonalFocus(season);
    const months = getSeasonMonths(season);

    return {
      season,
      chinese: SEASON_CHINESE[season],
      subtitle: SEASON_SUBTITLES[season],
      element: SEASON_ELEMENTS[season],
      storyArc: SEASON_STORY_ARCS[season],
      ritualArchetype: SEASON_RITUAL_ARCHETYPES[season],
      energeticTones,
      ceremonialFocus,
      personaWhisper: SEASON_WHISPERS[season],
      months
    };
  });
}

/**
 * Get energetic tones for a season
 */
function getSeasonalTones(season: LiturgicalSeason): GreatSeason['energeticTones'] {
  const toneMap: Record<LiturgicalSeason, GreatSeason['energeticTones']> = {
    spring: ['rising', 'opening', 'sprouting'],
    summer: ['heat', 'momentum', 'expression'],
    autumn: ['cutting', 'refining', 'clarifying'],
    winter: ['depth', 'stillness', 'reflection']
  };
  return toneMap[season];
}

/**
 * Get ceremonial focus areas for a season
 */
function getSeasonalFocus(season: LiturgicalSeason): string[] {
  const focusMap: Record<LiturgicalSeason, string[]> = {
    spring: ['Vows', 'New intentions', 'First steps', 'Planting seeds'],
    summer: ['Building', 'Commitment', 'Courage', 'Visibility'],
    autumn: ['Letting go', 'Truth-telling', 'Reorientation', 'Decision'],
    winter: ['Healing', 'Closure', 'Rest', 'Renewal']
  };
  return focusMap[season];
}

/**
 * Get which months belong to a season
 */
function getSeasonMonths(season: LiturgicalSeason): number[] {
  const monthMap: Record<LiturgicalSeason, number[]> = {
    spring: [1, 2, 3],
    summer: [4, 5, 6],
    autumn: [7, 8, 9],
    winter: [10, 11, 12]
  };
  return monthMap[season];
}

/**
 * Get the current season based on a date
 */
export function getCurrentSeason(date: Date = new Date()): LiturgicalSeason {
  const month = date.getMonth() + 1; // 1-12

  if (month >= 1 && month <= 3) return 'spring';
  if (month >= 4 && month <= 6) return 'summer';
  if (month >= 7 && month <= 9) return 'autumn';
  return 'winter';
}

/**
 * Get a great season by identifier
 */
export function getGreatSeason(season: LiturgicalSeason): GreatSeason {
  return generateGreatSeasons().find(s => s.season === season)!;
}

// ============================================================================
// MONTH GENERATION
// ============================================================================

/**
 * Generate the twelve ritual months
 */
export function generateRitualMonths(): RitualMonth[] {
  const months: RitualMonthNumber[] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];

  return months.map(month => {
    const season = getSeasonForMonth(month);

    return {
      month,
      name: RITUAL_MONTH_NAMES[month],
      chinese: RITUAL_MONTH_CHINESE[month],
      theme: RITUAL_MONTH_THEMES[month],
      storyBeat: RITUAL_MONTH_STORY_BEATS[month],
      ritual: RITUAL_MONTH_RITUALS[month],
      season,
      description: generateMonthDescription(month)
    };
  });
}

/**
 * Get the season for a given month
 */
function getSeasonForMonth(month: RitualMonthNumber): LiturgicalSeason {
  if (month >= 1 && month <= 3) return 'spring';
  if (month >= 4 && month <= 6) return 'summer';
  if (month >= 7 && month <= 9) return 'autumn';
  return 'winter';
}

/**
 * Generate description for a month
 */
function generateMonthDescription(month: RitualMonthNumber): string {
  const descriptions: Record<RitualMonthNumber, string> = {
    1: 'The year awakens. Set your intentions with clarity and purpose.',
    2: 'New growth emerges. Nurture what has begun.',
    3: 'Movement accelerates. Align your direction with the winds.',
    4: 'Fire rises within. Let courage guide your actions.',
    5: 'Peak energy arrives. Stand in your fullest expression.',
    6: 'The heat begins to soften. Prepare for transition.',
    7: 'Look into the mirror. Face what is true.',
    8: 'The blade falls. Cut away what no longer serves.',
    9: 'Gather the harvest. Honor what has grown.',
    10: 'Descend into depth. Embrace the shadows.',
    11: 'Embers glow. Healing emerges from the darkness.',
    12: 'Seeds form in silence. Prepare for the next cycle.'
  };
  return descriptions[month];
}

/**
 * Get the current ritual month
 */
export function getCurrentRitualMonth(date: Date = new Date()): RitualMonth {
  const month = (date.getMonth() + 1) as RitualMonthNumber;
  return generateRitualMonths().find(m => m.month === month)!;
}

/**
 * Get a specific ritual month
 */
export function getRitualMonth(month: RitualMonthNumber): RitualMonth {
  return generateRitualMonths().find(m => m.month === month)!;
}

// ============================================================================
// WEEK GENERATION
// ============================================================================

/**
 * Generate the fifty-two story weeks for a year
 */
export function generateStoryWeeks(year: number = new Date().getFullYear()): StoryWeek[] {
  const weeks: StoryWeek[] = [];

  for (let weekNum = 1; weekNum <= 52; weekNum++) {
    const beatIndex = (weekNum - 1) % WEEKLY_BEAT_CYCLE.length;
    const storyBeat = WEEKLY_BEAT_CYCLE[beatIndex];
    const month = Math.ceil(weekNum / 4.33) as RitualMonthNumber;
    const season = getSeasonForMonth(Math.min(month, 12) as RitualMonthNumber);

    weeks.push({
      weekNumber: weekNum,
      storyBeat,
      month: Math.min(month, 12) as RitualMonthNumber,
      season,
      theme: generateWeekTheme(weekNum, storyBeat),
      ritualPrompt: generateWeekRitualPrompt(storyBeat),
      storyGuidance: generateWeekStoryGuidance(storyBeat),
      timingInsight: generateWeekTimingInsight(weekNum, storyBeat)
    });
  }

  return weeks;
}

/**
 * Generate a theme for a week
 */
function generateWeekTheme(weekNum: number, beat: WeeklyStoryBeat): string {
  return `Week ${weekNum}: The ${beat.charAt(0).toUpperCase() + beat.slice(1)}`;
}

/**
 * Generate ritual prompt for a week
 */
function generateWeekRitualPrompt(beat: WeeklyStoryBeat): string {
  const prompts: Record<WeeklyStoryBeat, string> = {
    spark: 'Light a candle. Set an intention. Begin.',
    rising: 'Build on what has started. Add energy.',
    tension: 'Notice where resistance appears. Hold steady.',
    break: 'Allow something to release. Breathe.',
    insight: 'Sit in stillness. Let understanding come.',
    shift: 'Change one thing. Move in a new direction.',
    integration: 'Let the new become natural. Rest.'
  };
  return prompts[beat];
}

/**
 * Generate story guidance for a week
 */
function generateWeekStoryGuidance(beat: WeeklyStoryBeat): string {
  return WEEKLY_BEAT_DESCRIPTIONS[beat];
}

/**
 * Generate timing insight for a week
 */
function generateWeekTimingInsight(weekNum: number, beat: WeeklyStoryBeat): string {
  const insights: Record<WeeklyStoryBeat, string> = {
    spark: 'Best for beginnings. Monday and Thursday are strong.',
    rising: 'Momentum builds mid-week. Wednesday peaks.',
    tension: 'Pressure points Tuesday and Friday. Handle with care.',
    break: 'Release comes naturally Friday evening.',
    insight: 'Saturday morning brings clarity.',
    shift: 'Sunday afternoon opens new paths.',
    integration: 'Rest Monday. Let it settle.'
  };
  return insights[beat];
}

/**
 * Get the current story week
 */
export function getCurrentStoryWeek(date: Date = new Date()): StoryWeek {
  const startOfYear = new Date(date.getFullYear(), 0, 1);
  const dayOfYear = Math.floor((date.getTime() - startOfYear.getTime()) / (24 * 60 * 60 * 1000));
  const weekNumber = Math.ceil(dayOfYear / 7);

  return generateStoryWeeks(date.getFullYear())[Math.min(weekNumber - 1, 51)];
}

// ============================================================================
// DAILY CYCLE
// ============================================================================

/**
 * Generate the four daily quadrants
 */
export function generateDailyQuadrants(): DailyQuadrant[] {
  const quadrants: DayQuadrant[] = ['morning', 'afternoon', 'evening', 'night'];

  return quadrants.map(quadrant => ({
    quadrant,
    action: QUADRANT_ACTIONS[quadrant],
    chinese: QUADRANT_CHINESE[quadrant],
    hourRange: QUADRANT_HOURS[quadrant],
    focus: getQuadrantFocus(quadrant),
    guidance: getQuadrantGuidance(quadrant)
  }));
}

/**
 * Get focus activities for a quadrant
 */
function getQuadrantFocus(quadrant: DayQuadrant): string[] {
  const focus: Record<DayQuadrant, string[]> = {
    morning: ['Set intention', 'Align direction', "Open the day's story"],
    afternoon: ['Act', 'Build', 'Engage'],
    evening: ['Reflect', 'Release', 'Soften'],
    night: ['Dream', 'Absorb', 'Prepare for tomorrow']
  };
  return focus[quadrant];
}

/**
 * Get guidance for a quadrant
 */
function getQuadrantGuidance(quadrant: DayQuadrant): string {
  const guidance: Record<DayQuadrant, string> = {
    morning: 'The day opens like a flower. What do you choose to tend?',
    afternoon: 'Energy flows outward. Let your actions speak.',
    evening: 'The day softens. What will you release before rest?',
    night: 'Silence descends. Let the deep mind integrate.'
  };
  return guidance[quadrant];
}

/**
 * Get the current quadrant
 */
export function getCurrentQuadrant(date: Date = new Date()): DailyQuadrant {
  const hour = date.getHours();

  if (hour >= 6 && hour < 12) return generateDailyQuadrants()[0]; // morning
  if (hour >= 12 && hour < 18) return generateDailyQuadrants()[1]; // afternoon
  if (hour >= 18 && hour < 22) return generateDailyQuadrants()[2]; // evening
  return generateDailyQuadrants()[3]; // night
}

/**
 * Generate a complete ritual day
 */
export function generateRitualDay(date: Date = new Date()): RitualDay {
  const week = getCurrentStoryWeek(date);
  const month = getCurrentRitualMonth(date);
  const festival = getFestivalForDate(date);

  return {
    date,
    weekNumber: week.weekNumber,
    month: month.month,
    season: month.season,
    quadrants: generateDailyQuadrants(),
    storyBeat: week.storyBeat,
    festival: festival || undefined,
    theme: generateDayTheme(date, week, month)
  };
}

/**
 * Generate a theme for a specific day
 */
function generateDayTheme(date: Date, week: StoryWeek, month: RitualMonth): string {
  const dayOfWeek = date.toLocaleDateString('en-US', { weekday: 'long' });
  return `${dayOfWeek} of ${week.storyBeat.charAt(0).toUpperCase() + week.storyBeat.slice(1)} in the ${month.name}`;
}

// ============================================================================
// TIMING WINDOWS
// ============================================================================

/**
 * Generate timing windows for a day
 */
export function generateDailyTimingWindows(date: Date = new Date()): DailyTimingWindows {
  const majorWindows = generateMajorWindows(date);
  const minorWindows = generateMinorWindows(date);
  const microWindows = generateMicroWindows(date);

  // Find optimal window
  const allWindows = [...majorWindows, ...minorWindows];
  const optimalWindow = allWindows.reduce((best, w) =>
    w.timingScore > best.timingScore ? w : best, allWindows[0]
  );

  return {
    date,
    majorWindows,
    minorWindows,
    microWindows,
    optimalWindow
  };
}

/**
 * Generate 4 major windows
 */
function generateMajorWindows(date: Date): TimingWindow[] {
  const quadrants = generateDailyQuadrants();

  return quadrants.map((q, index) => ({
    id: `major-${index + 1}`,
    size: 'major' as const,
    startTime: { hour: q.hourRange[0], minute: 0 },
    endTime: { hour: q.hourRange[1], minute: 0 },
    ritualArchetype: q.action,
    storyBeat: q.focus[0],
    timingScore: 60 + Math.random() * 40,
    goodFor: q.focus
  }));
}

/**
 * Generate 12 minor windows (2-hour blocks)
 */
function generateMinorWindows(date: Date): TimingWindow[] {
  const windows: TimingWindow[] = [];

  for (let i = 0; i < 12; i++) {
    const startHour = (i * 2) % 24;
    const endHour = ((i + 1) * 2) % 24;

    windows.push({
      id: `minor-${i + 1}`,
      size: 'minor' as const,
      startTime: { hour: startHour, minute: 0 },
      endTime: { hour: endHour, minute: 0 },
      ritualArchetype: getHourArchetype(startHour),
      storyBeat: getHourStoryBeat(startHour),
      timingScore: 40 + Math.random() * 60,
      goodFor: getHourActivities(startHour)
    });
  }

  return windows;
}

/**
 * Generate 48 micro windows (30-minute blocks)
 */
function generateMicroWindows(date: Date): TimingWindow[] {
  const windows: TimingWindow[] = [];

  for (let i = 0; i < 48; i++) {
    const startHour = Math.floor(i / 2);
    const startMinute = (i % 2) * 30;
    const endHour = Math.floor((i + 1) / 2) % 24;
    const endMinute = ((i + 1) % 2) * 30;

    windows.push({
      id: `micro-${i + 1}`,
      size: 'micro' as const,
      startTime: { hour: startHour, minute: startMinute },
      endTime: { hour: endHour, minute: endMinute },
      ritualArchetype: getHourArchetype(startHour),
      storyBeat: getHourStoryBeat(startHour),
      timingScore: 30 + Math.random() * 70,
      goodFor: getHourActivities(startHour)
    });
  }

  return windows;
}

/**
 * Get archetype for an hour
 */
function getHourArchetype(hour: number): string {
  if (hour >= 6 && hour < 12) return 'initiate';
  if (hour >= 12 && hour < 18) return 'act';
  if (hour >= 18 && hour < 22) return 'reflect';
  return 'rest';
}

/**
 * Get story beat for an hour
 */
function getHourStoryBeat(hour: number): string {
  if (hour >= 6 && hour < 9) return 'awakening';
  if (hour >= 9 && hour < 12) return 'building';
  if (hour >= 12 && hour < 15) return 'peak';
  if (hour >= 15 && hour < 18) return 'sustaining';
  if (hour >= 18 && hour < 21) return 'winding';
  return 'resting';
}

/**
 * Get activities good for an hour
 */
function getHourActivities(hour: number): string[] {
  if (hour >= 6 && hour < 9) return ['Meditation', 'Planning', 'Intention-setting'];
  if (hour >= 9 && hour < 12) return ['Deep work', 'Creation', 'Problem-solving'];
  if (hour >= 12 && hour < 15) return ['Meetings', 'Collaboration', 'Action'];
  if (hour >= 15 && hour < 18) return ['Review', 'Communication', 'Completion'];
  if (hour >= 18 && hour < 21) return ['Reflection', 'Connection', 'Unwinding'];
  return ['Rest', 'Dreaming', 'Integration'];
}

/**
 * Get current timing window
 */
export function getCurrentTimingWindow(date: Date = new Date()): TimingWindow {
  const windows = generateDailyTimingWindows(date);
  const hour = date.getHours();
  const minute = date.getMinutes();

  // Find matching minor window
  const windowIndex = Math.floor((hour * 2 + Math.floor(minute / 30)));
  return windows.microWindows[windowIndex % 48] || windows.majorWindows[0];
}

// ============================================================================
// FESTIVALS
// ============================================================================

/**
 * Generate the eight ceremonial festivals
 */
export function generateFestivals(): CeremonialFestival[] {
  const festivalData: Array<{
    type: FestivalType;
    season: LiturgicalSeason;
    celebrates: string;
    ritual: string;
    storySignificance: string;
    ceremonies: string[];
    blessing: string;
    date: { month: number; day: number };
  }> = [
    {
      type: 'first_breath',
      season: 'spring',
      celebrates: 'The beginning of spring',
      ritual: 'Vows',
      storySignificance: 'Story opens',
      ceremonies: ['Dawn vigil', 'Seed planting', 'Vow ceremony'],
      blessing: 'May your first breath of the year carry the seeds of your deepest intentions.',
      date: { month: 2, day: 4 }
    },
    {
      type: 'spring_gate',
      season: 'spring',
      celebrates: 'Spring equinox',
      ritual: 'Directional rites',
      storySignificance: 'Balance point',
      ceremonies: ['Sun salutation', 'Egg blessing', 'Balance meditation'],
      blessing: 'At the gate of equal light and shadow, may you find your center.',
      date: { month: 3, day: 20 }
    },
    {
      type: 'rising_flame',
      season: 'summer',
      celebrates: 'The beginning of summer',
      ritual: 'Courage',
      storySignificance: 'Momentum peaks',
      ceremonies: ['Fire lighting', 'Dance of courage', 'Peak declaration'],
      blessing: 'Let the rising flame illuminate your boldest self.',
      date: { month: 5, day: 5 }
    },
    {
      type: 'summer_gate',
      season: 'summer',
      celebrates: 'Summer solstice',
      ritual: 'Directional rites',
      storySignificance: 'Maximum light',
      ceremonies: ['Sunrise ceremony', 'Crown of fire', 'Longest day vigil'],
      blessing: 'At the peak of light, may your brilliance shine without restraint.',
      date: { month: 6, day: 21 }
    },
    {
      type: 'blade',
      season: 'autumn',
      celebrates: 'The beginning of autumn',
      ritual: 'Release',
      storySignificance: 'Turning point',
      ceremonies: ['Blade ceremony', 'Cutting rite', 'Release bonfire'],
      blessing: 'What the blade releases becomes the path forward.',
      date: { month: 8, day: 7 }
    },
    {
      type: 'autumn_gate',
      season: 'autumn',
      celebrates: 'Autumn equinox',
      ritual: 'Directional rites',
      storySignificance: 'Harvest balance',
      ceremonies: ['Harvest feast', 'Gratitude circle', 'Balance stone'],
      blessing: 'At the gate of harvest, may you gather what you have sown.',
      date: { month: 9, day: 22 }
    },
    {
      type: 'deep_water',
      season: 'winter',
      celebrates: 'The beginning of winter',
      ritual: 'Healing',
      storySignificance: 'Descent',
      ceremonies: ['Water blessing', 'Depth meditation', 'Healing circle'],
      blessing: 'In the deep water, may you find the healing that waits in darkness.',
      date: { month: 11, day: 7 }
    },
    {
      type: 'winter_gate',
      season: 'winter',
      celebrates: 'Winter solstice',
      ritual: 'Directional rites',
      storySignificance: 'Rebirth of light',
      ceremonies: ['Longest night vigil', 'Candle lighting', 'New sun welcome'],
      blessing: 'At the darkest gate, the first light of the new cycle is born.',
      date: { month: 12, day: 21 }
    }
  ];

  return festivalData.map(f => ({
    type: f.type,
    name: FESTIVAL_NAMES[f.type],
    chinese: FESTIVAL_CHINESE[f.type],
    season: f.season,
    celebrates: f.celebrates,
    ritual: f.ritual,
    storySignificance: f.storySignificance,
    ceremonies: f.ceremonies,
    blessing: f.blessing,
    approximateDate: f.date
  }));
}

/**
 * Get festival for a specific date (if any)
 */
export function getFestivalForDate(date: Date): CeremonialFestival | null {
  const month = date.getMonth() + 1;
  const day = date.getDate();

  const festivals = generateFestivals();
  return festivals.find(f =>
    f.approximateDate.month === month &&
    Math.abs(f.approximateDate.day - day) <= 1
  ) || null;
}

/**
 * Get the next upcoming festival
 */
export function getNextFestival(date: Date = new Date()): { festival: CeremonialFestival; daysUntil: number } {
  const festivals = generateFestivals();
  const year = date.getFullYear();

  let closestFestival = festivals[0];
  let minDays = Infinity;

  for (const festival of festivals) {
    let festDate = new Date(year, festival.approximateDate.month - 1, festival.approximateDate.day);

    // If festival has passed this year, check next year
    if (festDate < date) {
      festDate = new Date(year + 1, festival.approximateDate.month - 1, festival.approximateDate.day);
    }

    const daysUntil = Math.ceil((festDate.getTime() - date.getTime()) / (24 * 60 * 60 * 1000));

    if (daysUntil < minDays && daysUntil > 0) {
      minDays = daysUntil;
      closestFestival = festival;
    }
  }

  return { festival: closestFestival, daysUntil: minDays };
}

// ============================================================================
// COMPLETE CALENDAR GENERATION
// ============================================================================

/**
 * Generate the complete liturgical calendar
 */
export function generateLiturgicalCalendar(options: LiturgicalCalendarOptions = {}): LiturgicalCalendar {
  const year = options.year || new Date().getFullYear();
  const now = new Date();

  return {
    name: 'Cathedral Liturgical Calendar',
    chinese: '大教堂礼历',
    seasons: generateGreatSeasons(),
    months: generateRitualMonths(),
    festivals: generateFestivals(),
    dailyQuadrants: generateDailyQuadrants(),
    weeklyBeatCycle: WEEKLY_BEAT_CYCLE,
    year,
    generatedAt: now,
    currentPosition: getCurrentLiturgicalPosition(now)
  };
}

/**
 * Get the current position in the liturgical calendar
 */
export function getCurrentLiturgicalPosition(date: Date = new Date()): LiturgicalPosition {
  const season = getCurrentSeason(date);
  const month = getCurrentRitualMonth(date);
  const week = getCurrentStoryWeek(date);
  const quadrant = getCurrentQuadrant(date);
  const currentWindow = getCurrentTimingWindow(date);
  const activeFestival = getFestivalForDate(date);
  const { festival: nextFestival, daysUntil } = getNextFestival(date);

  return {
    date,
    season,
    month,
    week,
    quadrant,
    currentWindow,
    activeFestival: activeFestival || undefined,
    daysUntilNextFestival: daysUntil,
    nextFestival
  };
}

// ============================================================================
// FORMATTED OUTPUT
// ============================================================================

/**
 * Format the complete liturgical calendar
 */
export function formatLiturgicalCalendar(calendar: LiturgicalCalendar): string {
  return `
╔══════════════════════════════════════════════════════════════════════════════╗
║          🌟 ${calendar.name} (${calendar.chinese}) 🌟                       ║
║               Year ${calendar.year} — The Sacred Ceremonial Cycle           ║
╚══════════════════════════════════════════════════════════════════════════════╝

═══════════════════════════════════════════════════════════════════════════════
                        THE FOUR GREAT SEASONS
═══════════════════════════════════════════════════════════════════════════════
${calendar.seasons.map(s => `
🌿 ${s.subtitle} (${s.chinese})
   Element: ${s.element} | Arc: ${s.storyArc} | Ritual: ${s.ritualArchetype}
   The Persona whispers: "${s.personaWhisper}"
`).join('')}

═══════════════════════════════════════════════════════════════════════════════
                        THE TWELVE RITUAL MONTHS
═══════════════════════════════════════════════════════════════════════════════
${calendar.months.map(m => `
${m.month}. ${m.name} (${m.chinese})
   Theme: ${m.theme} | Story Beat: ${m.storyBeat} | Ritual: ${m.ritual}
`).join('')}

═══════════════════════════════════════════════════════════════════════════════
                      THE EIGHT CEREMONIAL FESTIVALS
═══════════════════════════════════════════════════════════════════════════════
${calendar.festivals.map(f => `
🎭 ${f.name} (${f.chinese})
   Season: ${f.season} | Celebrates: ${f.celebrates}
   Blessing: "${f.blessing}"
`).join('')}

═══════════════════════════════════════════════════════════════════════════════
                         THE DAILY RITUAL CYCLE
═══════════════════════════════════════════════════════════════════════════════
${calendar.dailyQuadrants.map(q => `
${q.quadrant.toUpperCase()} (${q.chinese}) — ${q.action.toUpperCase()}
   Hours: ${q.hourRange[0]}:00 - ${q.hourRange[1]}:00
   Focus: ${q.focus.join(', ')}
   "${q.guidance}"
`).join('')}

Generated: ${calendar.generatedAt.toISOString()}
`;
}

/**
 * Format the current liturgical position
 */
export function formatCurrentPosition(position: LiturgicalPosition): string {
  const festivalLine = position.activeFestival
    ? `\n🎭 ACTIVE FESTIVAL: ${position.activeFestival.name} (${position.activeFestival.chinese})\n   "${position.activeFestival.blessing}"`
    : '';

  return `
╔══════════════════════════════════════════════════════════════════════════════╗
║                    🌟 CURRENT LITURGICAL POSITION 🌟                          ║
╚══════════════════════════════════════════════════════════════════════════════╝

📅 Date: ${position.date.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}

🌿 Season: ${SEASON_CHINESE[position.season]} — ${SEASON_SUBTITLES[position.season]}
   Element: ${SEASON_ELEMENTS[position.season]}
   Story Arc: ${SEASON_STORY_ARCS[position.season]}
   "${SEASON_WHISPERS[position.season]}"

📆 Month: ${position.month.name} (${position.month.chinese})
   Theme: ${position.month.theme}
   Story Beat: ${position.month.storyBeat}
   Ritual: ${position.month.ritual}

📅 Week: ${position.week.weekNumber} — ${position.week.storyBeat.toUpperCase()}
   "${position.week.storyGuidance}"
   Ritual Prompt: ${position.week.ritualPrompt}

⏰ Quadrant: ${position.quadrant.quadrant.toUpperCase()} (${position.quadrant.chinese})
   Action: ${position.quadrant.action}
   "${position.quadrant.guidance}"

⏱️ Current Window: ${position.currentWindow.id}
   Timing Score: ${position.currentWindow.timingScore.toFixed(0)}%
   Good For: ${position.currentWindow.goodFor.join(', ')}
${festivalLine}

📍 Next Festival: ${position.nextFestival.name} in ${position.daysUntilNextFestival} days
`;
}

/**
 * Get a liturgical blessing for the current moment
 */
export function getLiturgicalBlessing(date: Date = new Date()): string {
  const position = getCurrentLiturgicalPosition(date);
  const season = getGreatSeason(position.season);

  return `
In this ${position.month.name},
in the season of ${season.subtitle},
in the week of ${position.week.storyBeat},
in the ${position.quadrant.quadrant} quadrant of ${position.quadrant.action}...

${season.personaWhisper}

${position.week.ritualPrompt}

${position.quadrant.guidance}

May the cathedral's rhythm guide your way.
`;
}
