/**
 * ============================================
 * GENERATIONAL STORY EXPORT LAYER
 * Turns the entire generational system into
 * a narrative artifact — a scroll, a scripture
 *
 * Exports to:
 * - Markdown (readable, shareable)
 * - HTML (printable, PDF-ready)
 * - JSON (data interchange)
 *
 * The pilgrim receives a complete lineage report.
 * ============================================
 */

import { GenerationalLadder, GenerationalThread, GenerationNode } from './generationalLadder';
import { PilgrimPosition, AncestralNarrative } from './journeyWithGenerations';
import { AncestralPersonaLayer, AncestralPersonaMessage } from './ancestralPersona';
import { RitualCollection, AncestralRitual } from './ancestralRitual';
import { GroupNarrative } from './narrativeFusion';

// ==================== DATA MODEL ====================

export interface GenerationalStoryData {
  lineageId: string;
  generatedAt: Date;
  pilgrimName?: string;
  ladder: GenerationalLadder;
  threads: GenerationalThread[];
  position: PilgrimPosition;
  narrative: AncestralNarrative;
  personaLayer?: AncestralPersonaLayer;
  rituals?: RitualCollection;
  generationNarratives?: Map<number, GroupNarrative>;
}

export interface ExportOptions {
  lang: 'en' | 'zh';
  includeRituals: boolean;
  includePersona: boolean;
  includeGenerationNarratives: boolean;
  theme: 'light' | 'dark' | 'parchment';
}

// ==================== MARKDOWN EXPORT ====================

/**
 * Generate complete Markdown export of generational story
 */
export function exportGenerationalStoryMarkdown(
  data: GenerationalStoryData,
  options: Partial<ExportOptions> = {}
): string {
  const { lang = 'en', includeRituals = true, includePersona = true, includeGenerationNarratives = true } = options;

  const title = lang === 'zh' ? '🕍 世代故事报告' : '🕍 Generational Story Report';
  const dateStr = data.generatedAt.toISOString().split('T')[0];

  const sections: string[] = [];

  // Header
  sections.push(`# ${title}`);
  sections.push('');
  sections.push(`**${lang === 'zh' ? '血脉' : 'Lineage'}:** ${data.lineageId}`);
  if (data.pilgrimName) {
    sections.push(`**${lang === 'zh' ? '行者' : 'Pilgrim'}:** ${data.pilgrimName}`);
  }
  sections.push(`**${lang === 'zh' ? '生成日期' : 'Generated'}:** ${dateStr}`);
  sections.push('');
  sections.push('---');
  sections.push('');

  // I. Generational Ladder
  sections.push(`## I. ${lang === 'zh' ? '世代阶梯' : 'Generational Ladder'}`);
  sections.push('');
  sections.push(renderLadderMarkdown(data.ladder, data.position, lang));
  sections.push('');

  // II. Ancestral Threads
  sections.push(`## II. ${lang === 'zh' ? '血脉丝线' : 'Ancestral Threads'}`);
  sections.push('');
  sections.push(renderThreadsMarkdown(data.threads, lang));
  sections.push('');

  // III. Pilgrim Position
  sections.push(`## III. ${lang === 'zh' ? '行者位置' : 'Pilgrim Position'}`);
  sections.push('');
  sections.push(renderPositionMarkdown(data.position, lang));
  sections.push('');

  // IV. Ancestral Narrative
  sections.push(`## IV. ${lang === 'zh' ? '血脉叙事' : 'Ancestral Narrative'}`);
  sections.push('');
  sections.push(renderNarrativeMarkdown(data.narrative, lang));
  sections.push('');

  // V. Ancestral Persona Messages (optional)
  if (includePersona && data.personaLayer) {
    sections.push(`## V. ${lang === 'zh' ? '祖系之声' : 'Ancestral Voices'}`);
    sections.push('');
    sections.push(renderPersonaMarkdown(data.personaLayer, lang));
    sections.push('');
  }

  // VI. Healing Rituals (optional)
  if (includeRituals && data.rituals) {
    sections.push(`## VI. ${lang === 'zh' ? '疗愈仪式' : 'Healing Rituals'}`);
    sections.push('');
    sections.push(renderRitualsMarkdown(data.rituals, lang));
    sections.push('');
  }

  // VII. Generation-by-Generation Narratives (optional)
  if (includeGenerationNarratives && data.generationNarratives) {
    sections.push(`## VII. ${lang === 'zh' ? '世代叙事' : 'Generation Narratives'}`);
    sections.push('');
    sections.push(renderGenerationNarrativesMarkdown(data.generationNarratives, data.ladder, lang));
    sections.push('');
  }

  // Footer
  sections.push('---');
  sections.push('');
  sections.push(`*${lang === 'zh' ? '由 Cathedral 生成' : 'Generated by Cathedral'}*`);

  return sections.join('\n');
}

// ==================== HTML EXPORT ====================

/**
 * Generate complete HTML export of generational story
 */
export function exportGenerationalStoryHtml(
  data: GenerationalStoryData,
  options: Partial<ExportOptions> = {}
): string {
  const { lang = 'en', includeRituals = true, includePersona = true, includeGenerationNarratives = true, theme = 'parchment' } = options;

  const title = lang === 'zh' ? '世代故事报告' : 'Generational Story Report';
  const dateStr = data.generatedAt.toISOString().split('T')[0];

  return `
<!DOCTYPE html>
<html lang="${lang === 'zh' ? 'zh-CN' : 'en'}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    ${getExportStyles(theme)}
  </style>
</head>
<body class="theme-${theme}">
  <article class="generational-story">
    <header class="story-header">
      <h1>🕍 ${title}</h1>
      <p class="meta">
        <strong>${lang === 'zh' ? '血脉' : 'Lineage'}:</strong> ${data.lineageId}<br>
        ${data.pilgrimName ? `<strong>${lang === 'zh' ? '行者' : 'Pilgrim'}:</strong> ${data.pilgrimName}<br>` : ''}
        <strong>${lang === 'zh' ? '生成日期' : 'Generated'}:</strong> ${dateStr}
      </p>
    </header>

    <section class="story-section">
      <h2>I. ${lang === 'zh' ? '世代阶梯' : 'Generational Ladder'}</h2>
      ${renderLadderHtml(data.ladder, data.position, lang)}
    </section>

    <section class="story-section">
      <h2>II. ${lang === 'zh' ? '血脉丝线' : 'Ancestral Threads'}</h2>
      ${renderThreadsHtml(data.threads, lang)}
    </section>

    <section class="story-section">
      <h2>III. ${lang === 'zh' ? '行者位置' : 'Pilgrim Position'}</h2>
      ${renderPositionHtml(data.position, lang)}
    </section>

    <section class="story-section">
      <h2>IV. ${lang === 'zh' ? '血脉叙事' : 'Ancestral Narrative'}</h2>
      ${renderNarrativeHtml(data.narrative, lang)}
    </section>

    ${includePersona && data.personaLayer ? `
    <section class="story-section">
      <h2>V. ${lang === 'zh' ? '祖系之声' : 'Ancestral Voices'}</h2>
      ${renderPersonaHtml(data.personaLayer, lang)}
    </section>
    ` : ''}

    ${includeRituals && data.rituals ? `
    <section class="story-section">
      <h2>VI. ${lang === 'zh' ? '疗愈仪式' : 'Healing Rituals'}</h2>
      ${renderRitualsHtml(data.rituals, lang)}
    </section>
    ` : ''}

    ${includeGenerationNarratives && data.generationNarratives ? `
    <section class="story-section">
      <h2>VII. ${lang === 'zh' ? '世代叙事' : 'Generation Narratives'}</h2>
      ${renderGenerationNarrativesHtml(data.generationNarratives, data.ladder, lang)}
    </section>
    ` : ''}

    <footer class="story-footer">
      <p>${lang === 'zh' ? '由 Cathedral 生成' : 'Generated by Cathedral'}</p>
    </footer>
  </article>
</body>
</html>
  `.trim();
}

// ==================== JSON EXPORT ====================

/**
 * Generate JSON export of generational story
 */
export function exportGenerationalStoryJson(data: GenerationalStoryData): string {
  return JSON.stringify({
    lineageId: data.lineageId,
    generatedAt: data.generatedAt.toISOString(),
    pilgrimName: data.pilgrimName,
    ladder: {
      generations: data.ladder.generations.map(g => ({
        generationIndex: g.generationIndex,
        label: g.label,
        labelZh: g.labelZh,
        memberCount: g.members.length,
        members: g.members.map(m => ({ id: m.id, name: m.name, birthDate: m.birthDate }))
      })),
      threadCount: data.ladder.threads.length
    },
    threads: data.threads.map(t => ({
      id: t.id,
      theme: t.theme,
      strength: t.strength,
      generations: t.generations
    })),
    position: {
      generationIndex: data.position.generationIndex,
      generationLabel: data.position.generationLabel,
      inheritedThemes: data.position.inheritedThemes,
      brokenPatterns: data.position.brokenPatterns,
      newPatterns: data.position.newPatterns,
      ancestorCount: data.position.ancestorCount,
      descendantCount: data.position.descendantCount
    },
    narrative: data.narrative,
    personaMessageCount: data.personaLayer?.messages.length ?? 0,
    ritualCount: data.rituals?.rituals.length ?? 0
  }, null, 2);
}

// ==================== MARKDOWN RENDERERS ====================

function renderLadderMarkdown(ladder: GenerationalLadder, position: PilgrimPosition, lang: 'en' | 'zh'): string {
  return ladder.generations
    .sort((a, b) => a.generationIndex - b.generationIndex)
    .map(gen => {
      const isSelf = gen.generationIndex === position.generationIndex;
      const marker = isSelf ? (lang === 'zh' ? ' ← **你**' : ' ← **YOU**') : '';
      const label = lang === 'zh' ? gen.labelZh || gen.label : gen.label;
      const members = gen.members.map(m => m.name).join(', ');

      return `### ${label}${marker}\n- ${lang === 'zh' ? '成员' : 'Members'}: ${members || (lang === 'zh' ? '无' : 'None')}`;
    }).join('\n\n');
}

function renderThreadsMarkdown(threads: GenerationalThread[], lang: 'en' | 'zh'): string {
  if (threads.length === 0) {
    return lang === 'zh' ? '*尚未检测到跨代丝线*' : '*No cross-generational threads detected*';
  }

  return threads.map(t => {
    const strengthLabel = t.strength >= 0.7 ? (lang === 'zh' ? '强' : 'Strong')
      : t.strength >= 0.4 ? (lang === 'zh' ? '中' : 'Moderate')
      : (lang === 'zh' ? '弱' : 'Faint');

    return `### ${t.theme}\n- **${lang === 'zh' ? '强度' : 'Strength'}:** ${strengthLabel} (${(t.strength * 100).toFixed(0)}%)\n- **${lang === 'zh' ? '跨越' : 'Spans'}:** ${t.generations.length} ${lang === 'zh' ? '代' : 'generations'}`;
  }).join('\n\n');
}

function renderPositionMarkdown(position: PilgrimPosition, lang: 'en' | 'zh'): string {
  const lines: string[] = [];

  lines.push(`**${lang === 'zh' ? '世代' : 'Generation'}:** ${lang === 'zh' ? position.generationLabelZh || position.generationLabel : position.generationLabel} (${position.generationIndex > 0 ? '+' : ''}${position.generationIndex})`);
  lines.push(`**${lang === 'zh' ? '祖先' : 'Ancestors'}:** ${position.ancestorCount} | **${lang === 'zh' ? '后代' : 'Descendants'}:** ${position.descendantCount}`);
  lines.push('');

  if (position.inheritedThemes.length > 0) {
    lines.push(`**${lang === 'zh' ? '继承的主题' : 'Inherited Themes'}:** ${position.inheritedThemes.join(', ')}`);
  }
  if (position.brokenPatterns.length > 0) {
    lines.push(`**${lang === 'zh' ? '终结的模式' : 'Broken Patterns'}:** ${position.brokenPatterns.join(', ')}`);
  }
  if (position.newPatterns.length > 0) {
    lines.push(`**${lang === 'zh' ? '开创的模式' : 'New Patterns'}:** ${position.newPatterns.join(', ')}`);
  }

  return lines.join('\n');
}

function renderNarrativeMarkdown(narrative: AncestralNarrative, lang: 'en' | 'zh'): string {
  const lines: string[] = [];

  lines.push(`### ${lang === 'zh' ? '血脉故事' : 'Lineage Story'}`);
  lines.push(lang === 'zh' ? narrative.lineageStoryZh || narrative.lineageStory : narrative.lineageStory);
  lines.push('');

  lines.push(`### ${lang === 'zh' ? '传承' : 'Inheritance'}`);
  lines.push(narrative.inheritanceStatement);
  lines.push('');

  lines.push(`### ${lang === 'zh' ? '解脱' : 'Liberation'}`);
  lines.push(narrative.liberationStatement);
  lines.push('');

  lines.push(`### ${lang === 'zh' ? '奠基' : 'Foundation'}`);
  lines.push(narrative.foundationStatement);
  lines.push('');

  lines.push(`### ${lang === 'zh' ? '祖系祝福' : 'Ancestral Blessing'}`);
  lines.push(`> ${lang === 'zh' ? narrative.ancestralBlessingZh || narrative.ancestralBlessing : narrative.ancestralBlessing}`);

  return lines.join('\n');
}

function renderPersonaMarkdown(personaLayer: AncestralPersonaLayer, lang: 'en' | 'zh'): string {
  const lines: string[] = [];

  lines.push(`> ${lang === 'zh' ? personaLayer.chorusVoiceZh || personaLayer.chorusVoice : personaLayer.chorusVoice}`);
  lines.push('');

  personaLayer.messages.forEach(msg => {
    const voiceLabel = getVoiceLabelText(msg.voice, lang);
    const text = lang === 'zh' ? msg.messageZh || msg.message : msg.message;
    lines.push(`**${voiceLabel}** (${msg.theme})`);
    lines.push(`> ${text}`);
    lines.push('');
  });

  lines.push(`> ${lang === 'zh' ? personaLayer.blessingVoiceZh || personaLayer.blessingVoice : personaLayer.blessingVoice}`);

  return lines.join('\n');
}

function renderRitualsMarkdown(rituals: RitualCollection, lang: 'en' | 'zh'): string {
  const lines: string[] = [];

  lines.push(`*${lang === 'zh' ? rituals.openingInvocationZh || rituals.openingInvocation : rituals.openingInvocation}*`);
  lines.push('');

  rituals.rituals.forEach((r, idx) => {
    lines.push(`### ${idx + 1}. ${lang === 'zh' ? r.titleZh || r.title : r.title}`);
    lines.push(`**${lang === 'zh' ? '意图' : 'Intention'}:** ${lang === 'zh' ? r.intentionZh || r.intention : r.intention}`);
    lines.push('');

    r.steps.forEach(step => {
      lines.push(`${step.order}. ${lang === 'zh' ? step.actionZh || step.action : step.action}`);
    });
    lines.push('');

    lines.push(`> ${lang === 'zh' ? r.ancestralVoiceZh || r.ancestralVoice : r.ancestralVoice}`);
    lines.push('');
  });

  lines.push(`*${lang === 'zh' ? rituals.closingBlessingZh || rituals.closingBlessing : rituals.closingBlessing}*`);

  return lines.join('\n');
}

function renderGenerationNarrativesMarkdown(
  narratives: Map<number, GroupNarrative>,
  ladder: GenerationalLadder,
  lang: 'en' | 'zh'
): string {
  const lines: string[] = [];

  ladder.generations
    .sort((a, b) => a.generationIndex - b.generationIndex)
    .forEach(gen => {
      const narrative = narratives.get(gen.generationIndex);
      if (!narrative) return;

      const label = lang === 'zh' ? gen.labelZh || gen.label : gen.label;
      lines.push(`### ${label}`);
      lines.push(narrative.summary.dominantThemes.slice(0, 3).join(', '));
      lines.push('');
    });

  return lines.join('\n');
}

// ==================== HTML RENDERERS ====================

function renderLadderHtml(ladder: GenerationalLadder, position: PilgrimPosition, lang: 'en' | 'zh'): string {
  return `
<div class="ladder-view">
  ${ladder.generations
    .sort((a, b) => a.generationIndex - b.generationIndex)
    .map(gen => {
      const isSelf = gen.generationIndex === position.generationIndex;
      const label = lang === 'zh' ? gen.labelZh || gen.label : gen.label;

      return `
<div class="ladder-rung ${isSelf ? 'is-self' : ''}">
  <span class="rung-label">${label}</span>
  ${isSelf ? `<span class="self-marker">${lang === 'zh' ? '← 你' : '← YOU'}</span>` : ''}
  <div class="rung-members">
    ${gen.members.map(m => `<span class="member">${m.name}</span>`).join('')}
  </div>
</div>
      `.trim();
    }).join('')}
</div>
  `.trim();
}

function renderThreadsHtml(threads: GenerationalThread[], lang: 'en' | 'zh'): string {
  if (threads.length === 0) {
    return `<p class="no-data">${lang === 'zh' ? '尚未检测到跨代丝线' : 'No cross-generational threads detected'}</p>`;
  }

  return `
<div class="threads-view">
  ${threads.map(t => `
<div class="thread-item">
  <strong>${t.theme}</strong>
  <span class="thread-strength">${(t.strength * 100).toFixed(0)}%</span>
  <span class="thread-span">${t.generations.length} ${lang === 'zh' ? '代' : 'gen'}</span>
</div>
  `.trim()).join('')}
</div>
  `.trim();
}

function renderPositionHtml(position: PilgrimPosition, lang: 'en' | 'zh'): string {
  return `
<div class="position-view">
  <div class="position-visual">
    <span class="ancestors">${position.ancestorCount} ${lang === 'zh' ? '祖先' : 'ancestors'}</span>
    <span class="arrow">←</span>
    <span class="self">${lang === 'zh' ? '你' : 'YOU'}</span>
    <span class="arrow">→</span>
    <span class="descendants">${position.descendantCount} ${lang === 'zh' ? '后代' : 'descendants'}</span>
  </div>
  <div class="position-themes">
    ${position.inheritedThemes.length > 0 ? `<div class="theme-group inherited"><strong>${lang === 'zh' ? '继承' : 'Inherited'}:</strong> ${position.inheritedThemes.join(', ')}</div>` : ''}
    ${position.brokenPatterns.length > 0 ? `<div class="theme-group broken"><strong>${lang === 'zh' ? '终结' : 'Broken'}:</strong> ${position.brokenPatterns.join(', ')}</div>` : ''}
    ${position.newPatterns.length > 0 ? `<div class="theme-group new"><strong>${lang === 'zh' ? '开创' : 'New'}:</strong> ${position.newPatterns.join(', ')}</div>` : ''}
  </div>
</div>
  `.trim();
}

function renderNarrativeHtml(narrative: AncestralNarrative, lang: 'en' | 'zh'): string {
  return `
<div class="narrative-view">
  <div class="lineage-story">
    <p>${lang === 'zh' ? narrative.lineageStoryZh || narrative.lineageStory : narrative.lineageStory}</p>
  </div>
  <blockquote class="ancestral-blessing">
    ${lang === 'zh' ? narrative.ancestralBlessingZh || narrative.ancestralBlessing : narrative.ancestralBlessing}
  </blockquote>
</div>
  `.trim();
}

function renderPersonaHtml(personaLayer: AncestralPersonaLayer, lang: 'en' | 'zh'): string {
  return `
<div class="persona-view">
  <blockquote class="chorus">${lang === 'zh' ? personaLayer.chorusVoiceZh || personaLayer.chorusVoice : personaLayer.chorusVoice}</blockquote>
  <div class="messages">
    ${personaLayer.messages.map(msg => `
    <div class="message">
      <span class="voice-label">${getVoiceLabelText(msg.voice, lang)}</span>
      <blockquote>${lang === 'zh' ? msg.messageZh || msg.message : msg.message}</blockquote>
    </div>
    `.trim()).join('')}
  </div>
  <blockquote class="blessing">${lang === 'zh' ? personaLayer.blessingVoiceZh || personaLayer.blessingVoice : personaLayer.blessingVoice}</blockquote>
</div>
  `.trim();
}

function renderRitualsHtml(rituals: RitualCollection, lang: 'en' | 'zh'): string {
  return `
<div class="rituals-view">
  <p class="invocation">${lang === 'zh' ? rituals.openingInvocationZh || rituals.openingInvocation : rituals.openingInvocation}</p>
  <div class="ritual-list">
    ${rituals.rituals.map((r, idx) => `
    <div class="ritual">
      <h4>${idx + 1}. ${lang === 'zh' ? r.titleZh || r.title : r.title}</h4>
      <ol>
        ${r.steps.map(s => `<li>${lang === 'zh' ? s.actionZh || s.action : s.action}</li>`).join('')}
      </ol>
      <blockquote>${lang === 'zh' ? r.ancestralVoiceZh || r.ancestralVoice : r.ancestralVoice}</blockquote>
    </div>
    `.trim()).join('')}
  </div>
  <p class="closing">${lang === 'zh' ? rituals.closingBlessingZh || rituals.closingBlessing : rituals.closingBlessing}</p>
</div>
  `.trim();
}

function renderGenerationNarrativesHtml(
  narratives: Map<number, GroupNarrative>,
  ladder: GenerationalLadder,
  lang: 'en' | 'zh'
): string {
  return `
<div class="gen-narratives-view">
  ${ladder.generations
    .sort((a, b) => a.generationIndex - b.generationIndex)
    .map(gen => {
      const narrative = narratives.get(gen.generationIndex);
      if (!narrative) return '';

      const label = lang === 'zh' ? gen.labelZh || gen.label : gen.label;
      return `
<div class="gen-narrative">
  <h4>${label}</h4>
  <p>${narrative.summary.dominantThemes.slice(0, 3).join(', ')}</p>
</div>
      `.trim();
    }).join('')}
</div>
  `.trim();
}

// ==================== STYLES ====================

function getExportStyles(theme: 'light' | 'dark' | 'parchment'): string {
  const themes = {
    light: { bg: '#fff', text: '#333', accent: '#667eea', border: '#e0e0e0' },
    dark: { bg: '#1a1a2e', text: '#e0e0e0', accent: '#9090ff', border: '#333' },
    parchment: { bg: '#faf7f3', text: '#3d3d3d', accent: '#8b4513', border: '#d4c4a8' }
  };
  const t = themes[theme];

  return `
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: Georgia, serif; background: ${t.bg}; color: ${t.text}; line-height: 1.8; padding: 40px; }
.generational-story { max-width: 800px; margin: 0 auto; }
.story-header { text-align: center; margin-bottom: 40px; }
.story-header h1 { font-size: 2rem; margin-bottom: 16px; }
.meta { font-size: 0.9rem; color: ${t.text}; opacity: 0.8; }
.story-section { margin-bottom: 40px; padding-bottom: 20px; border-bottom: 1px solid ${t.border}; }
.story-section h2 { font-size: 1.3rem; margin-bottom: 16px; color: ${t.accent}; }
.ladder-rung { padding: 12px; margin-bottom: 8px; background: rgba(0,0,0,0.03); border-radius: 8px; }
.ladder-rung.is-self { border-left: 4px solid ${t.accent}; }
.self-marker { color: ${t.accent}; font-weight: bold; margin-left: 8px; }
.thread-item { padding: 8px; margin-bottom: 6px; }
.position-visual { display: flex; justify-content: center; gap: 16px; padding: 20px; }
.position-visual .self { background: ${t.accent}; color: #fff; padding: 8px 16px; border-radius: 8px; }
blockquote { padding: 16px; background: rgba(0,0,0,0.03); border-left: 4px solid ${t.accent}; margin: 16px 0; font-style: italic; }
.story-footer { text-align: center; margin-top: 40px; font-size: 0.85rem; opacity: 0.6; }
@media print { body { padding: 20px; } .story-section { page-break-inside: avoid; } }
  `.trim();
}

// ==================== HELPERS ====================

function getVoiceLabelText(voice: string, lang: 'en' | 'zh'): string {
  const labels: Record<string, { en: string; zh: string }> = {
    chorus: { en: 'Ancestor Chorus', zh: '祖系合唱' },
    echo: { en: 'Generational Echo', zh: '世代回响' },
    thread: { en: 'Ancestral Thread', zh: '血脉丝线' },
    witness: { en: 'Ancestral Witness', zh: '见证者之声' }
  };
  return labels[voice]?.[lang] || voice;
}

// ==================== EXPORTS ====================

export {
  exportGenerationalStoryMarkdown,
  exportGenerationalStoryHtml,
  exportGenerationalStoryJson,
  type GenerationalStoryData,
  type ExportOptions
};
