/**
 * ============================================================================
 * BAZI STEM-BRANCH RELATIONS ENGINE
 * ============================================================================
 *
 * Analyzes the relationship between the Heavenly Stem and Earthly Branch
 * within each pillar of the BaZi chart.
 *
 * Classical Doctrine:
 * The stem "sits" on the branch. The relationship between them determines:
 * - Rootedness: Is the stem supported by its branch?
 * - Transparency: Is the stem's energy clearly expressed?
 * - Strength: How much power does the stem receive?
 *
 * Key Relationships:
 * 1. SAME ELEMENT (通根 Tong Gen) - Stem rooted in branch = strong support
 * 2. GENERATED BY (得生 De Sheng) - Branch element generates stem = support
 * 3. GENERATES BRANCH (泄气 Xie Qi) - Stem generates branch = draining
 * 4. CONTROLLED BY (被克 Bei Ke) - Branch element controls stem = weakening
 * 5. CONTROLS BRANCH (克制 Ke Zhi) - Stem controls branch = exhausting
 *
 * Created: January 2026
 * Based on: Classical BaZi stem-branch relationship doctrine
 * ============================================================================
 */

import { Element } from './baziSeasonality';

// ============================================================================
// ELEMENT MAPPINGS
// ============================================================================

/**
 * Heavenly Stem to Element mapping
 */
export const STEM_ELEMENT: Record<string, Element> = {
  '甲': 'wood', '乙': 'wood',
  '丙': 'fire', '丁': 'fire',
  '戊': 'earth', '己': 'earth',
  '庚': 'metal', '辛': 'metal',
  '壬': 'water', '癸': 'water'
};

/**
 * Earthly Branch main element
 * Each branch has a dominant element (the "main qi")
 */
export const BRANCH_MAIN_ELEMENT: Record<string, Element> = {
  '子': 'water',  // Rat - pure Water
  '丑': 'earth',  // Ox - Earth (with Water, Metal hidden)
  '寅': 'wood',   // Tiger - Wood (with Fire, Earth hidden)
  '卯': 'wood',   // Rabbit - pure Wood
  '辰': 'earth',  // Dragon - Earth (with Wood, Water hidden)
  '巳': 'fire',   // Snake - Fire (with Earth, Metal hidden)
  '午': 'fire',   // Horse - Fire (with Earth hidden)
  '未': 'earth',  // Goat - Earth (with Fire, Wood hidden)
  '申': 'metal',  // Monkey - Metal (with Water, Earth hidden)
  '酉': 'metal',  // Rooster - pure Metal
  '戌': 'earth',  // Dog - Earth (with Metal, Fire hidden)
  '亥': 'water'   // Pig - Water (with Wood hidden)
};

/**
 * Hidden stems within each branch
 * Order: [Main Qi, Middle Qi, Residual Qi]
 * Not all branches have all three
 */
export const BRANCH_HIDDEN_STEMS: Record<string, string[]> = {
  '子': ['癸'],              // Gui Water only
  '丑': ['己', '癸', '辛'],   // Ji Earth, Gui Water, Xin Metal
  '寅': ['甲', '丙', '戊'],   // Jia Wood, Bing Fire, Wu Earth
  '卯': ['乙'],              // Yi Wood only
  '辰': ['戊', '乙', '癸'],   // Wu Earth, Yi Wood, Gui Water
  '巳': ['丙', '戊', '庚'],   // Bing Fire, Wu Earth, Geng Metal
  '午': ['丁', '己'],        // Ding Fire, Ji Earth
  '未': ['己', '丁', '乙'],   // Ji Earth, Ding Fire, Yi Wood
  '申': ['庚', '壬', '戊'],   // Geng Metal, Ren Water, Wu Earth
  '酉': ['辛'],              // Xin Metal only
  '戌': ['戊', '辛', '丁'],   // Wu Earth, Xin Metal, Ding Fire
  '亥': ['壬', '甲']         // Ren Water, Jia Wood
};

// ============================================================================
// ELEMENT CYCLES
// ============================================================================

/**
 * Generation cycle (生 Sheng): What element does this one produce?
 */
export const GENERATES: Record<Element, Element> = {
  wood: 'fire',
  fire: 'earth',
  earth: 'metal',
  metal: 'water',
  water: 'wood'
};

/**
 * Control cycle (克 Ke): What element does this one control?
 */
export const CONTROLS: Record<Element, Element> = {
  wood: 'earth',
  earth: 'water',
  water: 'fire',
  fire: 'metal',
  metal: 'wood'
};

/**
 * Reverse lookups
 */
export const GENERATED_BY: Record<Element, Element> = {
  wood: 'water',
  fire: 'wood',
  earth: 'fire',
  metal: 'earth',
  water: 'metal'
};

export const CONTROLLED_BY: Record<Element, Element> = {
  wood: 'metal',
  fire: 'water',
  earth: 'wood',
  metal: 'fire',
  water: 'earth'
};

// ============================================================================
// TYPES
// ============================================================================

export type RelationType =
  | 'rooted'       // Same element - strong support
  | 'supported'    // Branch generates stem - moderate support
  | 'drained'      // Stem generates branch - mild weakening
  | 'controlled'   // Branch controls stem - weakening
  | 'exhausting'   // Stem controls branch - mild exhausting
  | 'neutral';     // No direct relationship

export interface StemBranchRelation {
  pillarName: string;
  stem: string;
  stemElement: Element;
  branch: string;
  branchMainElement: Element;
  hiddenStems: string[];
  hiddenElements: Element[];
  relation: RelationType;
  strengthModifier: number;  // 0.7 - 1.3 range
  hasRoot: boolean;          // Is stem's element found in branch's hidden stems?
  rootStrength: number;      // 0 if no root, 0.3-1.0 based on position in hidden
  explanation: string;
}

export interface ChartStemBranchAnalysis {
  pillars: StemBranchRelation[];
  dayMasterRelation: StemBranchRelation;
  overallRootedness: number;        // 0-1 scale
  rootedPillarCount: number;        // How many pillars have the stem rooted
  strongestSupport: string;         // Which pillar provides strongest support
  weakestLink: string;              // Which pillar is most challenged
  dmHasStrongRoot: boolean;         // Is Day Master well-rooted?
  explanation: string;
}

export interface FourPillars {
  year: { stem: string; branch: string };
  month: { stem: string; branch: string };
  day: { stem: string; branch: string };
  hour: { stem: string; branch: string };
}

// ============================================================================
// CORE FUNCTIONS
// ============================================================================

/**
 * Analyze the stem-branch relationship for a single pillar
 *
 * @param stem - Heavenly Stem character (e.g., "甲")
 * @param branch - Earthly Branch character (e.g., "寅")
 * @param pillarName - Name of the pillar (year, month, day, hour)
 * @returns StemBranchRelation with detailed analysis
 */
export function computeStemBranchRelation(
  stem: string,
  branch: string,
  pillarName: string = 'pillar'
): StemBranchRelation {
  const stemElement = STEM_ELEMENT[stem] || 'wood';
  const branchMainElement = BRANCH_MAIN_ELEMENT[branch] || 'wood';
  const hiddenStems = BRANCH_HIDDEN_STEMS[branch] || [];
  const hiddenElements = hiddenStems.map(s => STEM_ELEMENT[s] || 'wood');

  // Check for root (stem's element in hidden stems)
  const hasRoot = hiddenElements.includes(stemElement);
  let rootStrength = 0;

  if (hasRoot) {
    // Position matters: Main Qi (index 0) is strongest
    const rootIndex = hiddenElements.indexOf(stemElement);
    rootStrength = rootIndex === 0 ? 1.0 : (rootIndex === 1 ? 0.6 : 0.3);
  }

  // Determine relationship type and strength modifier
  let relation: RelationType;
  let strengthModifier: number;

  if (stemElement === branchMainElement || hasRoot) {
    // Same element or rooted = strong support
    relation = 'rooted';
    strengthModifier = 1.0 + (rootStrength * 0.3); // 1.0 to 1.3
  } else if (GENERATED_BY[stemElement] === branchMainElement) {
    // Branch generates stem = support
    relation = 'supported';
    strengthModifier = 1.1;
  } else if (GENERATES[stemElement] === branchMainElement) {
    // Stem generates branch = drained
    relation = 'drained';
    strengthModifier = 0.9;
  } else if (CONTROLLED_BY[stemElement] === branchMainElement) {
    // Branch controls stem = weakened
    relation = 'controlled';
    strengthModifier = 0.8;
  } else if (CONTROLS[stemElement] === branchMainElement) {
    // Stem controls branch = exhausting effort
    relation = 'exhausting';
    strengthModifier = 0.85;
  } else {
    relation = 'neutral';
    strengthModifier = 1.0;
  }

  const explanation = generateRelationExplanation(
    pillarName,
    stem,
    stemElement,
    branch,
    branchMainElement,
    relation,
    hasRoot,
    rootStrength
  );

  return {
    pillarName,
    stem,
    stemElement,
    branch,
    branchMainElement,
    hiddenStems,
    hiddenElements,
    relation,
    strengthModifier,
    hasRoot,
    rootStrength,
    explanation
  };
}

/**
 * Analyze stem-branch relations for all four pillars
 *
 * @param pillars - Four Pillars with stem and branch for each
 * @returns ChartStemBranchAnalysis with comprehensive analysis
 */
export function computeChartStemBranchRelations(
  pillars: FourPillars
): ChartStemBranchAnalysis {
  const pillarKeys = ['year', 'month', 'day', 'hour'] as const;

  const pillarRelations = pillarKeys.map(key =>
    computeStemBranchRelation(pillars[key].stem, pillars[key].branch, key)
  );

  // Extract day master relation
  const dayMasterRelation = pillarRelations.find(p => p.pillarName === 'day')!;

  // Count rooted pillars
  const rootedPillarCount = pillarRelations.filter(p => p.hasRoot).length;

  // Calculate overall rootedness (weighted average)
  const pillarWeights = { year: 0.15, month: 0.25, day: 0.40, hour: 0.20 };
  let overallRootedness = 0;

  pillarRelations.forEach(p => {
    const weight = pillarWeights[p.pillarName as keyof typeof pillarWeights] || 0.25;
    overallRootedness += p.rootStrength * weight;
  });

  // Normalize to 0-1
  overallRootedness = Math.min(1, overallRootedness);

  // Find strongest support and weakest link
  const sorted = [...pillarRelations].sort((a, b) => b.strengthModifier - a.strengthModifier);
  const strongestSupport = sorted[0].pillarName;
  const weakestLink = sorted[sorted.length - 1].pillarName;

  // Is Day Master well-rooted?
  const dmHasStrongRoot = dayMasterRelation.hasRoot && dayMasterRelation.rootStrength >= 0.6;

  const explanation = generateChartExplanation(
    pillarRelations,
    dayMasterRelation,
    overallRootedness,
    rootedPillarCount,
    dmHasStrongRoot
  );

  return {
    pillars: pillarRelations,
    dayMasterRelation,
    overallRootedness,
    rootedPillarCount,
    strongestSupport,
    weakestLink,
    dmHasStrongRoot,
    explanation
  };
}

// ============================================================================
// HELPERS
// ============================================================================

function generateRelationExplanation(
  pillarName: string,
  stem: string,
  stemElement: Element,
  branch: string,
  branchMainElement: Element,
  relation: RelationType,
  hasRoot: boolean,
  rootStrength: number
): string {
  const stemName = capitalize(stemElement);
  const branchName = capitalize(branchMainElement);
  const pillarTitle = capitalize(pillarName);

  let explanation = `${pillarTitle} Pillar: ${stem} ${stemName} on ${branch} ${branchName}\n\n`;

  const relationMessages: Record<RelationType, string> = {
    rooted: `The ${stemName} stem finds its root in the ${branch} branch. This is excellent support - like a tree with deep roots.`,
    supported: `The ${branchName} branch generates ${stemName}. The stem receives nourishing support from below.`,
    drained: `The ${stemName} stem generates the ${branchName} branch. Energy flows outward - productive but slightly draining.`,
    controlled: `The ${branchName} branch controls ${stemName}. The stem faces pressure from its foundation.`,
    exhausting: `The ${stemName} stem controls the ${branchName} branch. Dominance requires constant effort.`,
    neutral: `The ${stemName} stem and ${branchName} branch have no direct elemental relationship.`
  };

  explanation += relationMessages[relation];

  if (hasRoot) {
    const strengthLabel = rootStrength >= 0.8 ? 'main qi' : (rootStrength >= 0.5 ? 'middle qi' : 'residual qi');
    explanation += `\n\nRoot found in branch's ${strengthLabel} (strength: ${(rootStrength * 100).toFixed(0)}%).`;
  }

  return explanation;
}

function generateChartExplanation(
  pillarRelations: StemBranchRelation[],
  dayMasterRelation: StemBranchRelation,
  overallRootedness: number,
  rootedPillarCount: number,
  dmHasStrongRoot: boolean
): string {
  let explanation = `Chart Stem-Branch Analysis\n${'='.repeat(30)}\n\n`;

  // Summary stats
  explanation += `Rooted Pillars: ${rootedPillarCount}/4\n`;
  explanation += `Overall Rootedness: ${(overallRootedness * 100).toFixed(0)}%\n\n`;

  // Day Master focus
  explanation += `Day Master (${dayMasterRelation.stem} ${capitalize(dayMasterRelation.stemElement)}):\n`;

  if (dmHasStrongRoot) {
    explanation += `Well-rooted in the ${dayMasterRelation.branch} branch. `;
    explanation += `Your core self has a strong foundation and clear expression.\n\n`;
  } else if (dayMasterRelation.hasRoot) {
    explanation += `Has moderate root in the ${dayMasterRelation.branch} branch. `;
    explanation += `Your foundation is present but could use strengthening.\n\n`;
  } else {
    explanation += `Not rooted in the ${dayMasterRelation.branch} branch. `;
    explanation += `Your Day Master must draw strength from other pillars or luck cycles.\n\n`;
  }

  // Pillar summary
  explanation += `Pillar Relations:\n`;
  pillarRelations.forEach(p => {
    const icon = p.hasRoot ? ' (rooted)' : '';
    explanation += `- ${capitalize(p.pillarName)}: ${p.relation}${icon}\n`;
  });

  // Classical interpretation
  explanation += `\nClassical Interpretation:\n`;
  if (overallRootedness >= 0.7) {
    explanation += `Strong overall rootedness indicates a chart where stems express themselves clearly and receive good support from their branches.`;
  } else if (overallRootedness >= 0.4) {
    explanation += `Moderate rootedness - some stems have support while others must work harder. This creates an interesting dynamic of strengths and growth areas.`;
  } else {
    explanation += `Limited rootedness means the stems often work without strong foundational support. This can indicate adaptability but also the need for external support from luck cycles.`;
  }

  return explanation;
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

// ============================================================================
// EXPORTS
// ============================================================================

export default {
  computeStemBranchRelation,
  computeChartStemBranchRelations,
  STEM_ELEMENT,
  BRANCH_MAIN_ELEMENT,
  BRANCH_HIDDEN_STEMS,
  GENERATES,
  CONTROLS,
  GENERATED_BY,
  CONTROLLED_BY
};
