/**
 * ============================================================================
 * BAZI SEASONALITY ADJUSTMENT ENGINE
 * ============================================================================
 *
 * The True Seasonality Weighting System (with Earth transitions)
 *
 * In BaZi, the Month Branch determines the season, and the season determines
 * which elements are naturally strong or weak.
 *
 * Classical 四季土 (Four Season Earth) Doctrine:
 * - Spring (寅卯): Wood dominates
 * - Summer (巳午): Fire dominates
 * - Autumn (申酉): Metal dominates
 * - Winter (亥子): Water dominates
 * - Earth Transition Months (辰戌丑未): Earth dominates
 *
 * This affects Day Master strength, Ten Gods, relationships, and luck cycles.
 *
 * Created: January 2026
 * Based on: Classical BaZi seasonality doctrine
 * ============================================================================
 */

export type Element = "wood" | "fire" | "earth" | "metal" | "water";

export interface SeasonalityResult {
  season: string;
  seasonChinese: string;
  seasonEmoji: string;
  monthBranch: string;
  weights: Record<Element, number>;
  raw: Record<Element, number>;
  rawNormalized: Record<Element, number>;
  adjusted: Record<Element, number>;
  normalized: Record<Element, number>;  // Same as adjustedNormalized for backwards compat
  adjustedNormalized: Record<Element, number>;
  deltas: Record<Element, number>;  // Change in percentage points
  dominantBefore: Element;
  dominantAfter: Element;
  dominantChanged: boolean;
  explanation: string;
}

// ============================================================================
// SEASON MAPPING
// ============================================================================

const SEASON_MAP: Record<string, string> = {
  // Spring months
  "寅": "spring", "卯": "spring",
  // Summer months
  "巳": "summer", "午": "summer",
  // Autumn months
  "申": "autumn", "酉": "autumn",
  // Winter months
  "亥": "winter", "子": "winter",
  // Earth transition months (四季土)
  "辰": "earth_transition_spring_summer",
  "未": "earth_transition_summer_autumn",
  "戌": "earth_transition_autumn_winter",
  "丑": "earth_transition_winter_spring"
};

const SEASON_INFO: Record<string, { name: string; chinese: string; emoji: string }> = {
  spring: { name: "Spring", chinese: "春", emoji: "🌸" },
  summer: { name: "Summer", chinese: "夏", emoji: "☀️" },
  autumn: { name: "Autumn", chinese: "秋", emoji: "🍂" },
  winter: { name: "Winter", chinese: "冬", emoji: "❄️" },
  earth_transition_spring_summer: { name: "Late Spring (Earth)", chinese: "季春土", emoji: "🌿" },
  earth_transition_summer_autumn: { name: "Late Summer (Earth)", chinese: "季夏土", emoji: "🌾" },
  earth_transition_autumn_winter: { name: "Late Autumn (Earth)", chinese: "季秋土", emoji: "🍁" },
  earth_transition_winter_spring: { name: "Late Winter (Earth)", chinese: "季冬土", emoji: "🌱" }
};

// ============================================================================
// SEASONAL WEIGHTS
// ============================================================================

/**
 * Standard seasonal weights for non-transition months
 * The dominant element of the season gets 1.0 (full strength)
 * Related elements get progressively lower weights
 */
const SEASON_WEIGHTS: Record<string, Record<Element, number>> = {
  spring: {
    wood: 1.0,    // Wood thrives in Spring
    fire: 0.8,    // Fire is generated by Wood
    water: 0.6,   // Water generates Wood (supportive)
    earth: 0.4,   // Earth is controlled by Wood
    metal: 0.2    // Metal controls Wood (weakest)
  },
  summer: {
    fire: 1.0,    // Fire thrives in Summer
    earth: 0.8,   // Earth is generated by Fire
    wood: 0.6,    // Wood generates Fire (supportive)
    metal: 0.4,   // Metal is controlled by Fire
    water: 0.2    // Water controls Fire (weakest)
  },
  autumn: {
    metal: 1.0,   // Metal thrives in Autumn
    water: 0.8,   // Water is generated by Metal
    earth: 0.6,   // Earth generates Metal (supportive)
    fire: 0.4,    // Fire controls Metal
    wood: 0.2     // Wood is controlled by Metal (weakest)
  },
  winter: {
    water: 1.0,   // Water thrives in Winter
    wood: 0.8,    // Wood is generated by Water
    metal: 0.6,   // Metal generates Water (supportive)
    earth: 0.4,   // Earth controls Water
    fire: 0.2     // Fire is controlled by Water (weakest)
  }
};

/**
 * Earth Transition Month Mapping
 * During these months, Earth becomes dominant
 * The incoming season element gets 0.8, outgoing gets 0.6
 */
const EARTH_TRANSITION_MAP: Record<string, { incoming: Element; outgoing: Element }> = {
  "辰": { incoming: "fire", outgoing: "wood" },    // Spring → Summer (Dragon month)
  "未": { incoming: "metal", outgoing: "fire" },   // Summer → Autumn (Goat month)
  "戌": { incoming: "water", outgoing: "metal" },  // Autumn → Winter (Dog month)
  "丑": { incoming: "wood", outgoing: "water" }    // Winter → Spring (Ox month)
};

// ============================================================================
// CORE FUNCTIONS
// ============================================================================

/**
 * Get seasonal weights for a given month branch
 * Handles both regular seasons and Earth transition months
 */
export function getSeasonalWeights(monthBranch: string): Record<Element, number> {
  const season = SEASON_MAP[monthBranch];

  if (!season) {
    // Unknown branch, return neutral weights
    console.warn(`Unknown month branch: ${monthBranch}`);
    return { wood: 1.0, fire: 1.0, earth: 1.0, metal: 1.0, water: 1.0 };
  }

  // Non-transition seasons use standard weights
  if (!season.startsWith("earth_transition")) {
    return SEASON_WEIGHTS[season];
  }

  // Earth transition month - compute dynamic weights
  const transition = EARTH_TRANSITION_MAP[monthBranch];
  if (!transition) {
    return { wood: 1.0, fire: 1.0, earth: 1.0, metal: 1.0, water: 1.0 };
  }

  const { incoming, outgoing } = transition;

  // Start with Earth dominant, others at base level
  const weights: Record<Element, number> = {
    earth: 1.0,   // Earth dominates transition months
    wood: 0.4,    // Base level
    fire: 0.4,    // Base level
    metal: 0.4,   // Base level
    water: 0.4    // Base level
  };

  // Incoming season element is strengthening
  weights[incoming] = 0.8;
  // Outgoing season element is weakening
  weights[outgoing] = 0.6;

  return weights;
}

/**
 * Get season information for display
 */
export function getSeasonInfo(monthBranch: string): { name: string; chinese: string; emoji: string } {
  const season = SEASON_MAP[monthBranch];
  return SEASON_INFO[season] || { name: "Unknown", chinese: "?", emoji: "❓" };
}

/**
 * Get the dominant element from a distribution
 */
function getDominantElement(distribution: Record<Element, number>): Element {
  let maxElement: Element = "wood";
  let maxValue = -1;

  for (const [element, value] of Object.entries(distribution)) {
    if (value > maxValue) {
      maxValue = value;
      maxElement = element as Element;
    }
  }

  return maxElement;
}

/**
 * Apply seasonality adjustment to raw element distribution
 *
 * Formula:
 *   adjusted[element] = raw[element] * seasonal_weight[element]
 *   normalized[element] = adjusted[element] / sum(adjusted)
 *
 * @param raw - Raw element distribution (from stems + hidden stems)
 * @param monthBranch - Month Branch character (e.g., "寅", "卯", "辰")
 * @returns SeasonalityResult with weights, adjusted, normalized values
 */
export function applySeasonality(
  raw: Record<Element, number>,
  monthBranch: string
): SeasonalityResult {
  const weights = getSeasonalWeights(monthBranch);
  const seasonInfo = getSeasonInfo(monthBranch);
  const season = SEASON_MAP[monthBranch] || "unknown";

  // Normalize raw to percentages first
  const rawTotal = Object.values(raw).reduce((a, b) => a + b, 0);
  const rawNormalized: Record<Element, number> = {
    wood: rawTotal > 0 ? (raw.wood / rawTotal) * 100 : 20,
    fire: rawTotal > 0 ? (raw.fire / rawTotal) * 100 : 20,
    earth: rawTotal > 0 ? (raw.earth / rawTotal) * 100 : 20,
    metal: rawTotal > 0 ? (raw.metal / rawTotal) * 100 : 20,
    water: rawTotal > 0 ? (raw.water / rawTotal) * 100 : 20
  };

  // Apply weights to raw distribution
  const adjusted: Record<Element, number> = {
    wood: raw.wood * weights.wood,
    fire: raw.fire * weights.fire,
    earth: raw.earth * weights.earth,
    metal: raw.metal * weights.metal,
    water: raw.water * weights.water
  };

  // Calculate total for normalization
  const adjustedTotal = Object.values(adjusted).reduce((a, b) => a + b, 0);

  // Normalize adjusted to percentages (0-100)
  const adjustedNormalized: Record<Element, number> = {
    wood: adjustedTotal > 0 ? (adjusted.wood / adjustedTotal) * 100 : 0,
    fire: adjustedTotal > 0 ? (adjusted.fire / adjustedTotal) * 100 : 0,
    earth: adjustedTotal > 0 ? (adjusted.earth / adjustedTotal) * 100 : 0,
    metal: adjustedTotal > 0 ? (adjusted.metal / adjustedTotal) * 100 : 0,
    water: adjustedTotal > 0 ? (adjusted.water / adjustedTotal) * 100 : 0
  };

  // Calculate deltas (change in percentage points)
  const deltas: Record<Element, number> = {
    wood: adjustedNormalized.wood - rawNormalized.wood,
    fire: adjustedNormalized.fire - rawNormalized.fire,
    earth: adjustedNormalized.earth - rawNormalized.earth,
    metal: adjustedNormalized.metal - rawNormalized.metal,
    water: adjustedNormalized.water - rawNormalized.water
  };

  // Determine dominant elements
  const dominantBefore = getDominantElement(raw);
  const dominantAfter = getDominantElement(adjustedNormalized);

  // Generate explanation
  const explanation = generateExplanation(
    monthBranch,
    season,
    weights,
    dominantBefore,
    dominantAfter
  );

  return {
    season,
    seasonChinese: seasonInfo.chinese,
    seasonEmoji: seasonInfo.emoji,
    monthBranch,
    weights,
    raw,
    rawNormalized,
    adjusted,
    normalized: adjustedNormalized,  // Backwards compatibility
    adjustedNormalized,
    deltas,
    dominantBefore,
    dominantAfter,
    dominantChanged: dominantBefore !== dominantAfter,
    explanation
  };
}

/**
 * Generate educational explanation of the seasonality adjustment
 */
function generateExplanation(
  monthBranch: string,
  season: string,
  weights: Record<Element, number>,
  dominantBefore: Element,
  dominantAfter: Element
): string {
  const seasonInfo = getSeasonInfo(monthBranch);
  const isEarthTransition = season.startsWith("earth_transition");

  let explanation = `Born in ${seasonInfo.name} (${monthBranch} month), `;

  if (isEarthTransition) {
    const transition = EARTH_TRANSITION_MAP[monthBranch];
    if (transition) {
      explanation += `an Earth transition month. Earth (土) becomes dominant during this period, `;
      explanation += `with ${capitalize(transition.incoming)} strengthening (incoming season) `;
      explanation += `and ${capitalize(transition.outgoing)} weakening (outgoing season). `;
    }
  } else {
    const dominant = Object.entries(weights).find(([_, w]) => w === 1.0)?.[0] || "unknown";
    explanation += `when ${capitalize(dominant)} naturally thrives. `;
  }

  if (dominantBefore !== dominantAfter) {
    explanation += `This shifts your dominant element from ${capitalize(dominantBefore)} to ${capitalize(dominantAfter)}.`;
  } else {
    explanation += `Your dominant element ${capitalize(dominantAfter)} is strengthened by the season.`;
  }

  return explanation;
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

// ============================================================================
// COMPARISON UTILITIES
// ============================================================================

/**
 * Calculate the impact of seasonality on each element
 * Returns positive values for elements that gained strength,
 * negative for elements that weakened
 */
export function calculateSeasonalImpact(
  raw: Record<Element, number>,
  normalized: Record<Element, number>
): Record<Element, number> {
  // First normalize raw to percentages for fair comparison
  const rawTotal = Object.values(raw).reduce((a, b) => a + b, 0);

  return {
    wood: normalized.wood - (raw.wood / rawTotal * 100),
    fire: normalized.fire - (raw.fire / rawTotal * 100),
    earth: normalized.earth - (raw.earth / rawTotal * 100),
    metal: normalized.metal - (raw.metal / rawTotal * 100),
    water: normalized.water - (raw.water / rawTotal * 100)
  };
}

/**
 * Get elements that gained/lost strength due to seasonality
 */
export function getSeasonalGainersLosers(impact: Record<Element, number>): {
  gainers: Array<{ element: Element; change: number }>;
  losers: Array<{ element: Element; change: number }>;
} {
  const entries = Object.entries(impact) as Array<[Element, number]>;

  const gainers = entries
    .filter(([_, change]) => change > 0.5) // Threshold for significance
    .map(([element, change]) => ({ element, change }))
    .sort((a, b) => b.change - a.change);

  const losers = entries
    .filter(([_, change]) => change < -0.5)
    .map(([element, change]) => ({ element, change }))
    .sort((a, b) => a.change - b.change);

  return { gainers, losers };
}

// ============================================================================
// ELEMENT COLORS AND DISPLAY
// ============================================================================

export const ELEMENT_COLORS: Record<Element, string> = {
  wood: "#22c55e",   // Green
  fire: "#ef4444",   // Red
  earth: "#f59e0b",  // Amber/Yellow
  metal: "#9ca3af",  // Gray
  water: "#3b82f6"   // Blue
};

export const ELEMENT_EMOJIS: Record<Element, string> = {
  wood: "🌳",
  fire: "🔥",
  earth: "�ite",
  metal: "🪙",
  water: "💧"
};

export const ELEMENT_CHINESE: Record<Element, string> = {
  wood: "木",
  fire: "火",
  earth: "土",
  metal: "金",
  water: "水"
};

// ============================================================================
// EXPORTS
// ============================================================================

export default {
  applySeasonality,
  getSeasonalWeights,
  getSeasonInfo,
  calculateSeasonalImpact,
  getSeasonalGainersLosers,
  SEASON_MAP,
  SEASON_WEIGHTS,
  EARTH_TRANSITION_MAP,
  ELEMENT_COLORS,
  ELEMENT_EMOJIS,
  ELEMENT_CHINESE
};
