/**
 * INTEGRATION_EXAMPLE.jsx
 * How to integrate AI Compatibility Engine into existing components
 * 
 * This shows how to replace static MBTI data with AI-generated insights
 * that cache intelligently in Firebase.
 */

import React, { useState, useEffect } from 'react';
import { getCompatibilityInsights } from '../services/mbtiCompatibilityAI';

// ═══════════════════════════════════════════════════════
// EXAMPLE 1: Simple Component Usage
// ═══════════════════════════════════════════════════════

export function SimpleCompatibilityView({ typeA, typeB }) {
  const [insights, setInsights] = useState(null);
  const [loading, setLoading] = useState(true);
  const [fromCache, setFromCache] = useState(false);

  useEffect(() => {
    async function loadInsights() {
      setLoading(true);
      
      try {
        const result = await getCompatibilityInsights(typeA, typeB);
        setInsights(result.insights);
        setFromCache(result.fromCache);
      } catch (error) {
        console.error('Error loading insights:', error);
      }
      
      setLoading(false);
    }

    if (typeA && typeB) {
      loadInsights();
    }
  }, [typeA, typeB]);

  if (loading) {
    return <div>Analyzing compatibility...</div>;
  }

  if (!insights) {
    return <div>Unable to load compatibility analysis</div>;
  }

  return (
    <div>
      {/* Cache indicator */}
      <div className="text-sm text-gray-500 mb-4">
        {fromCache ? '⚡ Loaded from cache' : '🤖 Generated by AI'}
      </div>

      {/* Overall score */}
      <div className="text-4xl font-bold mb-4">
        {insights.overallCompatibility}% Compatible
      </div>

      {/* Strengths */}
      <div className="mb-6">
        <h3 className="font-bold mb-2">💪 Strengths</h3>
        <ul>
          {insights.analysis.strengths.map((strength, i) => (
            <li key={i}>{strength}</li>
          ))}
        </ul>
      </div>

      {/* Challenges */}
      <div className="mb-6">
        <h3 className="font-bold mb-2">⚠️ Challenges</h3>
        <ul>
          {insights.analysis.challenges.map((challenge, i) => (
            <li key={i}>{challenge}</li>
          ))}
        </ul>
      </div>

      {/* Metaphor */}
      <div className="bg-purple-100 p-4 rounded-lg">
        <h3 className="font-bold mb-2">{insights.metaphor.title}</h3>
        <p>{insights.metaphor.description}</p>
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════
// EXAMPLE 2: Integration with Existing CompatibilityDiscovery
// ═══════════════════════════════════════════════════════

export function EnhancedCompatibilityDiscovery({ userType, partnerType }) {
  const [insights, setInsights] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchInsights() {
      if (!userType || !partnerType) return;

      setLoading(true);
      
      try {
        // THIS IS THE MAGIC LINE - replaces all static data
        const result = await getCompatibilityInsights(userType, partnerType);
        setInsights(result);
      } catch (error) {
        console.error('Failed to fetch insights:', error);
      }
      
      setLoading(false);
    }

    fetchInsights();
  }, [userType, partnerType]);

  // Show loading state
  if (loading) {
    return (
      <div className="min-h-screen bg-slate-900 flex items-center justify-center">
        <div className="text-center">
          <div className="text-6xl mb-4">🧠</div>
          <div className="text-xl text-purple-400">
            AI is analyzing your compatibility...
          </div>
          <div className="text-sm text-purple-300 mt-2">
            {insights?.fromCache ? 'Loading from cache...' : 'Generating fresh insights...'}
          </div>
        </div>
      </div>
    );
  }

  // Show error state
  if (!insights) {
    return (
      <div className="min-h-screen bg-slate-900 flex items-center justify-center">
        <div className="text-center text-red-400">
          Unable to generate compatibility analysis
        </div>
      </div>
    );
  }

  // Main render with AI insights
  const { analysis, metaphor, advice } = insights.insights;

  return (
    <div className="min-h-screen bg-slate-900 p-8">
      {/* Cache indicator badge */}
      <div className="max-w-4xl mx-auto mb-4">
        <span className={`
          inline-block px-3 py-1 rounded-full text-xs
          ${insights.fromCache 
            ? 'bg-green-900 text-green-300' 
            : 'bg-blue-900 text-blue-300'}
        `}>
          {insights.fromCache ? '⚡ Instant (Cached)' : '🤖 AI Generated'}
        </span>
      </div>

      {/* Overall Score Circle */}
      <div className="max-w-4xl mx-auto mb-12">
        <div className="text-center">
          <div className="inline-block relative">
            {/* Score circle */}
            <div className="w-48 h-48 rounded-full bg-gradient-to-br from-purple-500 to-pink-600 flex items-center justify-center">
              <div className="text-6xl font-bold text-white">
                {insights.insights.overallCompatibility}%
              </div>
            </div>
            
            {/* Metaphor title */}
            <div className="mt-6 text-2xl font-bold text-purple-400">
              {metaphor.title}
            </div>
            <div className="mt-2 text-purple-300 max-w-md mx-auto">
              {metaphor.description}
            </div>
          </div>
        </div>
      </div>

      {/* Analysis Sections */}
      <div className="max-w-4xl mx-auto grid md:grid-cols-2 gap-8 mb-12">
        {/* Strengths */}
        <div className="bg-slate-800 rounded-2xl p-6">
          <h3 className="text-xl font-bold text-green-400 mb-4">
            💪 Natural Strengths
          </h3>
          <ul className="space-y-2">
            {analysis.strengths.map((strength, i) => (
              <li key={i} className="text-purple-300 flex items-start gap-2">
                <span className="text-green-400 mt-1">✓</span>
                <span>{strength}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Challenges */}
        <div className="bg-slate-800 rounded-2xl p-6">
          <h3 className="text-xl font-bold text-orange-400 mb-4">
            ⚠️ Growth Areas
          </h3>
          <ul className="space-y-2">
            {analysis.challenges.map((challenge, i) => (
              <li key={i} className="text-purple-300 flex items-start gap-2">
                <span className="text-orange-400 mt-1">!</span>
                <span>{challenge}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Communication Style */}
      <div className="max-w-4xl mx-auto mb-12">
        <div className="bg-slate-800 rounded-2xl p-8">
          <h3 className="text-2xl font-bold text-purple-400 mb-4">
            💬 Communication Style
          </h3>
          <p className="text-purple-300 text-lg leading-relaxed">
            {analysis.communicationStyle}
          </p>
        </div>
      </div>

      {/* Personalized Advice */}
      <div className="max-w-4xl mx-auto grid md:grid-cols-2 gap-8">
        {/* Advice for Type A */}
        <div className="bg-gradient-to-br from-purple-900 to-purple-800 rounded-2xl p-6">
          <div className="text-4xl mb-4">👤</div>
          <h3 className="text-xl font-bold text-purple-200 mb-3">
            For {userType}
          </h3>
          <p className="text-purple-100 leading-relaxed">
            {advice.forTypeA}
          </p>
        </div>

        {/* Advice for Type B */}
        <div className="bg-gradient-to-br from-pink-900 to-pink-800 rounded-2xl p-6">
          <div className="text-4xl mb-4">👥</div>
          <h3 className="text-xl font-bold text-pink-200 mb-3">
            For {partnerType}
          </h3>
          <p className="text-pink-100 leading-relaxed">
            {advice.forTypeB}
          </p>
        </div>
      </div>

      {/* Growth Areas for Each */}
      <div className="max-w-4xl mx-auto mt-8 grid md:grid-cols-2 gap-8">
        <div className="bg-slate-800 rounded-2xl p-6">
          <h4 className="text-lg font-bold text-purple-400 mb-3">
            Growth Areas for {userType}
          </h4>
          <ul className="space-y-2">
            {analysis.growthAreas.typeA.map((area, i) => (
              <li key={i} className="text-purple-300 flex items-start gap-2">
                <span className="text-purple-500">→</span>
                <span>{area}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="bg-slate-800 rounded-2xl p-6">
          <h4 className="text-lg font-bold text-pink-400 mb-3">
            Growth Areas for {partnerType}
          </h4>
          <ul className="space-y-2">
            {analysis.growthAreas.typeB.map((area, i) => (
              <li key={i} className="text-pink-300 flex items-start gap-2">
                <span className="text-pink-500">→</span>
                <span>{area}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Metadata footer */}
      <div className="max-w-4xl mx-auto mt-12 text-center text-xs text-purple-400">
        Generated: {new Date(insights.meta.generatedAt).toLocaleString()}
        {insights.meta.tokenUsage && (
          <span className="ml-4">
            • Tokens: {insights.meta.tokenUsage.total}
          </span>
        )}
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════
// EXAMPLE 3: Preloading for Performance
// ═══════════════════════════════════════════════════════

export function MBTIRoseWindowWithPreload({ currentType }) {
  const [preloadedTypes] = useState([
    'ISTJ', 'ISFJ', 'INFJ', 'INTJ',
    'ISTP', 'ISFP', 'INFP', 'INTP'
  ]);

  useEffect(() => {
    // Preload common type combinations in the background
    async function preload() {
      if (!currentType) return;

      // Preload first 3 types silently
      for (let i = 0; i < 3; i++) {
        const partnerType = preloadedTypes[i];
        if (partnerType === currentType) continue;

        try {
          // This will cache the result for instant display later
          await getCompatibilityInsights(currentType, partnerType);
          console.log(`✓ Preloaded ${currentType}-${partnerType}`);
        } catch (error) {
          console.warn(`Failed to preload ${partnerType}:`, error);
        }

        // Small delay between preloads to avoid rate limits
        await new Promise(resolve => setTimeout(resolve, 1000));
      }
    }

    preload();
  }, [currentType]);

  return (
    <div>
      {/* Your existing MBTIRoseWindow component */}
      {/* When user clicks a portal, insights load instantly from cache */}
    </div>
  );
}

// ═══════════════════════════════════════════════════════
// EXAMPLE 4: Migration Guide
// ═══════════════════════════════════════════════════════

/**
 * BEFORE (Static Data):
 * 
 * const compatibility = mbtiCompatibility[typeA][typeB];
 * 
 * AFTER (AI + Cache):
 * 
 * const result = await getCompatibilityInsights(typeA, typeB);
 * const compatibility = result.insights;
 * 
 * That's it! Everything else stays the same.
 * The AI engine handles:
 * - Cache checking
 * - AI generation (if needed)
 * - Firebase storage
 * - Token tracking
 * - Error handling
 * - Fallback data
 */

// ═══════════════════════════════════════════════════════
// EXAMPLE 5: Custom Hook Pattern
// ═══════════════════════════════════════════════════════

export function useCompatibilityInsights(typeA, typeB) {
  const [insights, setInsights] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [fromCache, setFromCache] = useState(false);

  useEffect(() => {
    let cancelled = false;

    async function load() {
      if (!typeA || !typeB) {
        setLoading(false);
        return;
      }

      setLoading(true);
      setError(null);

      try {
        const result = await getCompatibilityInsights(typeA, typeB);
        
        if (!cancelled) {
          setInsights(result.insights);
          setFromCache(result.fromCache);
          setLoading(false);
        }
      } catch (err) {
        if (!cancelled) {
          setError(err);
          setLoading(false);
        }
      }
    }

    load();

    return () => {
      cancelled = true;
    };
  }, [typeA, typeB]);

  return { insights, loading, error, fromCache };
}

// Usage:
// const { insights, loading, fromCache } = useCompatibilityInsights('ISTJ', 'ENFP');
