/**
 * ============================================
 * PRO REPORT AUTO-GENERATION ENGINE (Designer 4.0)
 * Full AI Editorial Engine
 *
 * Features:
 * - Auto-generates entire report
 * - Explains reasoning for each section
 * - Provides rationale for order, tone, emphasis
 * - Supports inline editing
 * - Dynamic re-flow as edits are made
 * ============================================
 */

import {
  buildProReportSections2,
  type ReportSection2,
  type ReportContext2
} from './proReportDesigner2';

import {
  suggestLayout,
  type LayoutSuggestion,
  type LayoutContext
} from './layoutSuggestionEngine';

import {
  TONE_PRESETS,
  getTonePreset,
  applyTone,
  applyToneToHeader,
  type TonePreset
} from './tonePresets';

// ==================== TYPES ====================

export interface AutoGeneratedSection {
  id: string;
  label: string;
  labelZh: string;
  content: string;
  contentZh: string;
  rationale: string;
  rationaleZh: string;
  isEmphasized: boolean;
  isEdited: boolean;
  editedContent?: string;
  editedContentZh?: string;
  order: number;
}

export interface AutoGeneratedReport {
  tone: TonePreset;
  layout: string[];
  sections: AutoGeneratedSection[];
  globalRationale: string[];
  globalRationaleZh: string[];
  focusAreas: string[];
  focusAreasZh: string[];
  confidence: number;
  generatedAt: Date;
  language: 'en' | 'zh';
}

export interface AutoGenOptions {
  language?: 'en' | 'zh';
  forceTone?: TonePreset;
  includeExtended?: boolean;
  maxSections?: number;
}

// ==================== AUTO-GENERATION ENGINE ====================

/**
 * Auto-generate complete report with rationale
 */
export function autoGenerateReport(
  ctx: ReportContext2,
  options: AutoGenOptions = {}
): AutoGeneratedReport {
  const language = options.language || 'en';

  // Build layout context
  const layoutContext: LayoutContext = {
    ctx,
    userPreferences: {
      wantsTiming: true,
      wantsNarrative: options.includeExtended,
      wantsGuidance: true
    }
  };

  // Get AI layout suggestions
  const suggestion = suggestLayout(layoutContext);

  // Determine tone (user override or AI suggestion)
  const tone = options.forceTone || suggestion.recommendedTone;
  const style = getTonePreset(tone);

  // Build base sections
  const baseSections = buildProReportSections2(ctx);

  // Generate sections with content and rationale
  const sections: AutoGeneratedSection[] = suggestion.recommendedOrder
    .slice(0, options.maxSections || 10)
    .map((id, index) => {
      const section = baseSections.find(s => s.id === id);
      if (!section) return null;

      const isEmphasized = suggestion.emphasize.includes(id);
      const sectionRationale = getSectionRationale(id, suggestion, ctx);

      // Generate content with tone applied
      const rawContent = section.renderer(ctx);
      const rawContentZh = section.rendererZh(ctx);

      const content = applyTone(
        applyToneToHeader(section.label, tone, 'en') + '\n\n' +
        rawContent.replace(/^###?\s+[^\n]+\n/, ''),
        tone,
        'en'
      );

      const contentZh = applyTone(
        applyToneToHeader(section.labelZh, tone, 'zh') + '\n\n' +
        rawContentZh.replace(/^###?\s+[^\n]+\n/, ''),
        tone,
        'zh'
      );

      return {
        id,
        label: section.label,
        labelZh: section.labelZh,
        content,
        contentZh,
        rationale: sectionRationale.en,
        rationaleZh: sectionRationale.zh,
        isEmphasized,
        isEdited: false,
        order: index + 1
      };
    })
    .filter(Boolean) as AutoGeneratedSection[];

  return {
    tone,
    layout: suggestion.recommendedOrder,
    sections,
    globalRationale: suggestion.rationale,
    globalRationaleZh: suggestion.rationaleZh,
    focusAreas: suggestion.focusAreas,
    focusAreasZh: suggestion.focusAreasZh,
    confidence: suggestion.confidence,
    generatedAt: new Date(),
    language
  };
}

/**
 * Get rationale for why a section was included
 */
function getSectionRationale(
  sectionId: string,
  suggestion: LayoutSuggestion,
  ctx: ReportContext2
): { en: string; zh: string } {
  const rationales: Record<string, { en: string; zh: string }> = {
    core: {
      en: 'The Core Chart section provides the fundamental four pillars data that all other analysis is built upon.',
      zh: '核心命盘部分提供所有其他分析建立的基础四柱数据。'
    },
    structure: {
      en: `Your chart follows the ${ctx.structure.type} pattern, which shapes your approach to career, relationships, and personal development.`,
      zh: `你的命盘遵循${ctx.structure.type}模式，这塑造你对事业、关系和个人发展的态度。`
    },
    ten_gods: {
      en: ctx.tenGods.length > 0
        ? `${ctx.tenGods.length} Ten God(s) detected in your chart, revealing key personality and relationship dynamics.`
        : 'Ten Gods analysis reveals the relational dynamics between elements in your chart.',
      zh: ctx.tenGods.length > 0
        ? `在你的命盘中检测到${ctx.tenGods.length}个十神，揭示关键的性格和关系动态。`
        : '十神分析揭示你命盘中元素之间的关系动态。'
    },
    useful_god: {
      en: ctx.usefulGods.length > 0
        ? `${ctx.usefulGods[0].element} has been identified as your Useful God, providing specific guidance for enhancement.`
        : 'Useful God analysis identifies which elements support your chart\'s balance.',
      zh: ctx.usefulGods.length > 0
        ? `${ctx.usefulGods[0].element}被确定为你的用神，提供具体的增强指导。`
        : '用神分析确定哪些元素支持你命盘的平衡。'
    },
    shen_sha: {
      en: ctx.shenSha.length > 0
        ? `${ctx.shenSha.length} Shen Sha star(s) detected, providing additional insights into your destiny patterns.`
        : 'Shen Sha analysis reveals special stars that influence your chart.',
      zh: ctx.shenSha.length > 0
        ? `检测到${ctx.shenSha.length}颗神煞星，提供对你命运模式的额外洞察。`
        : '神煞分析揭示影响你命盘的特殊星辰。'
    },
    luck_pillars: {
      en: ctx.luckPillars.current
        ? `You are currently in the ${ctx.luckPillars.current.stem} ${ctx.luckPillars.current.branch} luck pillar (ages ${ctx.luckPillars.current.startAge}-${ctx.luckPillars.current.endAge}), making timing analysis especially relevant.`
        : 'Luck Pillars show the 10-year cycles that shape your life journey.',
      zh: ctx.luckPillars.current
        ? `你目前处于${ctx.luckPillars.current.stem}${ctx.luckPillars.current.branch}大运（${ctx.luckPillars.current.startAge}-${ctx.luckPillars.current.endAge}岁），使时机分析特别相关。`
        : '大运显示塑造你人生旅程的十年周期。'
    },
    annual: {
      en: ctx.annual
        ? `${ctx.annual.year} is a ${ctx.annual.stem} ${ctx.annual.branch} year, bringing specific themes and opportunities.`
        : 'Annual forecast shows how the current year\'s energy interacts with your chart.',
      zh: ctx.annual
        ? `${ctx.annual.year}年是${ctx.annual.stem}${ctx.annual.branch}年，带来特定的主题和机会。`
        : '流年预测显示当年能量如何与你的命盘互动。'
    },
    guidance: {
      en: 'Actionable Guidance translates your chart analysis into practical steps you can take.',
      zh: '行动指南将你的命盘分析转化为你可以采取的实际步骤。'
    }
  };

  // Add emphasis rationale if applicable
  const base = rationales[sectionId] || {
    en: 'This section provides additional insights into your chart.',
    zh: '此部分提供对你命盘的额外洞察。'
  };

  if (suggestion.emphasize.includes(sectionId)) {
    return {
      en: base.en + ' This section is emphasized based on your chart patterns.',
      zh: base.zh + ' 根据你的命盘模式，此部分被强调。'
    };
  }

  return base;
}

// ==================== EDITING OPERATIONS ====================

/**
 * Edit a section's content
 */
export function editSection(
  report: AutoGeneratedReport,
  sectionId: string,
  newContent: string,
  language: 'en' | 'zh' = 'en'
): AutoGeneratedReport {
  return {
    ...report,
    sections: report.sections.map(s => {
      if (s.id !== sectionId) return s;

      if (language === 'zh') {
        return {
          ...s,
          isEdited: true,
          editedContentZh: newContent
        };
      }

      return {
        ...s,
        isEdited: true,
        editedContent: newContent
      };
    })
  };
}

/**
 * Revert section to original content
 */
export function revertSection(
  report: AutoGeneratedReport,
  sectionId: string
): AutoGeneratedReport {
  return {
    ...report,
    sections: report.sections.map(s => {
      if (s.id !== sectionId) return s;
      return {
        ...s,
        isEdited: false,
        editedContent: undefined,
        editedContentZh: undefined
      };
    })
  };
}

/**
 * Reorder sections
 */
export function reorderAutoGenSections(
  report: AutoGeneratedReport,
  newOrder: string[]
): AutoGeneratedReport {
  const reorderedSections = newOrder
    .map((id, index) => {
      const section = report.sections.find(s => s.id === id);
      if (!section) return null;
      return { ...section, order: index + 1 };
    })
    .filter(Boolean) as AutoGeneratedSection[];

  return {
    ...report,
    layout: newOrder,
    sections: reorderedSections
  };
}

/**
 * Toggle section enabled/disabled
 */
export function toggleAutoGenSection(
  report: AutoGeneratedReport,
  sectionId: string
): AutoGeneratedReport {
  const section = report.sections.find(s => s.id === sectionId);

  if (section) {
    // Remove section
    return {
      ...report,
      layout: report.layout.filter(id => id !== sectionId),
      sections: report.sections.filter(s => s.id !== sectionId)
    };
  }

  // Section not in report - would need to regenerate to add
  return report;
}

/**
 * Change report tone
 */
export function changeTone(
  report: AutoGeneratedReport,
  newTone: TonePreset,
  ctx: ReportContext2
): AutoGeneratedReport {
  // Regenerate with new tone but preserve edits
  const newReport = autoGenerateReport(ctx, {
    language: report.language,
    forceTone: newTone
  });

  // Preserve edited sections
  return {
    ...newReport,
    sections: newReport.sections.map(newSection => {
      const oldSection = report.sections.find(s => s.id === newSection.id);
      if (oldSection?.isEdited) {
        return {
          ...newSection,
          isEdited: true,
          editedContent: oldSection.editedContent,
          editedContentZh: oldSection.editedContentZh
        };
      }
      return newSection;
    })
  };
}

// ==================== RENDERING ====================

/**
 * Render final report content
 */
export function renderAutoGenReport(
  report: AutoGeneratedReport,
  options: { includeRationale?: boolean } = {}
): string {
  const lang = report.language;

  let output = '';

  // Header
  output += `# BaZi Pro Report\n\n`;
  output += `*Generated: ${report.generatedAt.toLocaleDateString()}*\n`;
  output += `*Tone: ${TONE_PRESETS[report.tone].name}*\n`;
  output += `*Confidence: ${(report.confidence * 100).toFixed(0)}%*\n\n`;

  // Focus Areas
  if (report.focusAreas.length > 0) {
    output += `## Key Focus Areas\n\n`;
    const areas = lang === 'zh' ? report.focusAreasZh : report.focusAreas;
    areas.forEach(area => {
      output += `- ${area}\n`;
    });
    output += '\n';
  }

  // Sections
  for (const section of report.sections.sort((a, b) => a.order - b.order)) {
    const content = section.isEdited
      ? (lang === 'zh' ? section.editedContentZh || section.contentZh : section.editedContent || section.content)
      : (lang === 'zh' ? section.contentZh : section.content);

    output += `${content}\n\n`;

    if (options.includeRationale) {
      const rationale = lang === 'zh' ? section.rationaleZh : section.rationale;
      output += `> *Why this section: ${rationale}*\n\n`;
    }

    output += `---\n\n`;
  }

  // Global Rationale
  if (options.includeRationale && report.globalRationale.length > 0) {
    output += `## AI Reasoning\n\n`;
    const rationale = lang === 'zh' ? report.globalRationaleZh : report.globalRationale;
    rationale.forEach(r => {
      output += `- ${r}\n`;
    });
  }

  return output;
}

/**
 * Export report as JSON
 */
export function exportAutoGenReportJson(report: AutoGeneratedReport): string {
  return JSON.stringify(report, null, 2);
}

/**
 * Get section for editing UI
 */
export function getSectionForEditing(
  report: AutoGeneratedReport,
  sectionId: string
): AutoGeneratedSection | undefined {
  return report.sections.find(s => s.id === sectionId);
}

/**
 * Get all editable sections
 */
export function getEditableSections(report: AutoGeneratedReport): Array<{
  id: string;
  label: string;
  content: string;
  rationale: string;
  isEdited: boolean;
  order: number;
}> {
  const lang = report.language;

  return report.sections
    .sort((a, b) => a.order - b.order)
    .map(s => ({
      id: s.id,
      label: lang === 'zh' ? s.labelZh : s.label,
      content: s.isEdited
        ? (lang === 'zh' ? s.editedContentZh || s.contentZh : s.editedContent || s.content)
        : (lang === 'zh' ? s.contentZh : s.content),
      rationale: lang === 'zh' ? s.rationaleZh : s.rationale,
      isEdited: s.isEdited,
      order: s.order
    }));
}

// ==================== QUICK AUTO-GEN ====================

/**
 * Quick auto-generate for common use cases
 */
export function quickAutoGenReport(
  ctx: ReportContext2,
  preset: 'comprehensive' | 'timing' | 'personality' | 'guidance' = 'comprehensive'
): AutoGeneratedReport {
  const presetOptions: Record<string, AutoGenOptions> = {
    comprehensive: { maxSections: 8 },
    timing: { maxSections: 4, forceTone: 'professional' },
    personality: { maxSections: 5, forceTone: 'poetic' },
    guidance: { maxSections: 3, forceTone: 'coaching' }
  };

  return autoGenerateReport(ctx, presetOptions[preset]);
}

// ==================== EXPORTS ====================

export {
  autoGenerateReport,
  editSection,
  revertSection,
  reorderAutoGenSections,
  toggleAutoGenSection,
  changeTone,
  renderAutoGenReport,
  exportAutoGenReportJson,
  getSectionForEditing,
  getEditableSections,
  quickAutoGenReport
};
